<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>meta-transform-binding</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meta.Core" Version="$(MetaFoundationPackageVersion)" />
    <ProjectReference Include="..\..\..\..\meta\MetaCli\Core\MetaCli.Core.csproj" />
    <ProjectReference Include="..\MetaTransform.Binding.csproj" />
    <ProjectReference Include="..\Tooling\MetaTransformBinding.Tooling.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="meta-transform-binding.MetaCli\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
