<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MetaAnalytics\Core\MetaAnalytics.Core.csproj" />
    <ProjectReference Include="..\..\MetaMultiDimensional\Core\MetaMultiDimensional.Core.csproj" />
  </ItemGroup>

</Project>
