// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaDataQuality
// Regenerate with:
//   meta generate csharp --workspace ".\MetaDataQuality" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaDataQuality
{
    public sealed class JoinPatternKeyPart
    {
        public string Id { get; set; } = string.Empty;

        public string BooleanComparisonExpressionId { get; set; } = string.Empty;

        public string? FirstExpressionDisplay { get; set; }

        public string FirstExpressionId { get; set; } = string.Empty;

        public string Ordinal { get; set; } = string.Empty;

        public string? SecondExpressionDisplay { get; set; }

        public string SecondExpressionId { get; set; } = string.Empty;

        public JoinPattern JoinPattern { get; set; } = null!;

    }
}
