<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkerProtocol\MetaOrchestration.WorkerProtocol.csproj" />
    <ProjectReference Include="..\Model\MetaOrchestration.Model.csproj" />
    <ProjectReference Include="..\..\MetaPipeline\Model\MetaPipeline.Model.csproj" />
    <ProjectReference Include="..\..\MetaTransform\Binding\MetaTransform.Binding.csproj" />
  </ItemGroup>

</Project>
