// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTabular
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTabular" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaTabular
{
    public sealed class TabularRelationship
    {
        public string Id { get; set; } = string.Empty;

        public string Cardinality { get; set; } = string.Empty;

        public string? CrossFilterDirection { get; set; }

        public string? IsActive { get; set; }

        public string? IsRequired { get; set; }

        public string Name { get; set; } = string.Empty;

        public TabularColumn FromColumn { get; set; } = null!;

        public TabularTable FromTable { get; set; } = null!;

        public TabularColumn ToColumn { get; set; } = null!;

        public TabularTable ToTable { get; set; } = null!;

    }
}
