// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTabular
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTabular" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaTabular
{
    public sealed class TabularHierarchyTranslation
    {
        public string Id { get; set; } = string.Empty;

        public string? Caption { get; set; }

        public string? Description { get; set; }

        public TabularCulture TabularCulture { get; set; } = null!;

        public TabularHierarchy TabularHierarchy { get; set; } = null!;

    }
}
