// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTabular
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTabular" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaTabular
{
    public sealed class TabularModel
    {
        public string Id { get; set; } = string.Empty;

        public string? Collation { get; set; }

        public string? CompatibilityLevel { get; set; }

        public string? DefaultCulture { get; set; }

        public string? DefaultDataView { get; set; }

        public string? Description { get; set; }

        public string Name { get; set; } = string.Empty;

    }
}
