// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTabular
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTabular" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaTabular
{
    public sealed class TabularPerspectiveHierarchy
    {
        public string Id { get; set; } = string.Empty;

        public TabularHierarchy TabularHierarchy { get; set; } = null!;

        public TabularPerspective TabularPerspective { get; set; } = null!;

    }
}
