// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTabular
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTabular" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaTabular
{
    public sealed class TabularCalculationItem
    {
        public string Id { get; set; } = string.Empty;

        public string? Description { get; set; }

        public string Expression { get; set; } = string.Empty;

        public string? FormatStringExpression { get; set; }

        public string Name { get; set; } = string.Empty;

        public string Ordinal { get; set; } = string.Empty;

        public TabularCalculationGroup TabularCalculationGroup { get; set; } = null!;

    }
}
