<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meta.Operations" Version="$(MetaFoundationPackageVersion)" />
    <PackageReference Include="Meta.Integration" Version="$(MetaFoundationPackageVersion)" />
    <PackageReference Include="MetaWeave.Core" Version="$(MetaFoundationPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MetaDataWarehouse\Core\MetaDataWarehouse.Core.csproj" />
    <ProjectReference Include="..\..\MetaDataType\Core\MetaDataType.Core.csproj" />
    <ProjectReference Include="..\..\MetaDataTypeConversion\Core\MetaDataTypeConversion.Core.csproj" />
    <ProjectReference Include="..\..\MetaSql\CSharp\MetaSql.CSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Weaves\DataWarehouseToSql\**\*">
      <Link>Weaves\DataWarehouseToSql\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>true</Pack>
      <PackagePath>contentFiles\any\any\Weaves\DataWarehouseToSql\%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
  </ItemGroup>

</Project>
