<Project>
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)Build\CliVersion.cs" Link="CliVersion.cs" Condition="'$(OutputType)' == 'Exe'" />
  </ItemGroup>

  <PropertyGroup>
    <MetaRepoRoot Condition="'$(MetaRepoRoot)' == ''">$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\meta\'))</MetaRepoRoot>
  </PropertyGroup>

  <ItemGroup Condition="Exists('$(MetaRepoRoot)Meta\Core\Meta.Core.csproj')">
    <PackageReference Remove="Meta.Core" />
    <ProjectReference Include="$(MetaRepoRoot)Meta\Core\Meta.Core.csproj" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(MetaRepoRoot)Meta\Surfaces\Meta.Surfaces.csproj')">
    <PackageReference Remove="Meta.Surfaces" />
    <ProjectReference Include="$(MetaRepoRoot)Meta\Surfaces\Meta.Surfaces.csproj" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(MetaRepoRoot)Meta\Integration\Meta.Integration.csproj')">
    <PackageReference Remove="Meta.Integration" />
    <ProjectReference Include="$(MetaRepoRoot)Meta\Integration\Meta.Integration.csproj" />
  </ItemGroup>
</Project>
