<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Workspace\MetaSql.meta.cs" Link="MetaSql.meta.cs" />
    <Compile Include="..\DeployManifest\Workspace\MetaSqlDeployManifest.meta.cs" Link="MetaSqlDeployManifest.meta.cs" />
  </ItemGroup>

</Project>
