// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaAnalytics
// Regenerate with:
//   meta generate csharp --workspace ".\MetaAnalytics" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaAnalytics
{
    public sealed class AttributeRelationship
    {
        public string Id { get; set; } = string.Empty;

        public string? Description { get; set; }

        public string? RelationshipType { get; set; }

        public Attribute ChildAttribute { get; set; } = null!;

        public Attribute ParentAttribute { get; set; } = null!;

    }
}
