// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaAnalytics
// Regenerate with:
//   meta generate csharp --workspace ".\MetaAnalytics" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaAnalytics
{
    public sealed class PerspectiveMeasure
    {
        public string Id { get; set; } = string.Empty;

        public Measure Measure { get; set; } = null!;

        public Perspective Perspective { get; set; } = null!;

    }
}
