<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meta.Integration" Version="$(MetaFoundationPackageVersion)" />
    <ProjectReference Include="..\Model\MetaAnalytics.Model.csproj" />
  </ItemGroup>

</Project>
