<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meta.Core" Version="$(MetaFoundationPackageVersion)" />
    <PackageReference Include="Meta.Integration" Version="$(MetaFoundationPackageVersion)" />
    <PackageReference Include="Meta.Operations" Version="$(MetaFoundationPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MetaDataVault\Core\MetaDataVault.Core.csproj" />
    <ProjectReference Include="..\..\MetaDataType\Core\MetaDataType.Core.csproj" />
    <ProjectReference Include="..\..\MetaDataTypeConversion\Core\MetaDataTypeConversion.Core.csproj" />
    <ProjectReference Include="..\..\MetaSql\CSharp\MetaSql.CSharp.csproj" />
  </ItemGroup>

</Project>
