<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>meta-data-quality</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meta.Core" Version="$(MetaFoundationPackageVersion)" />
    <ProjectReference Include="..\..\..\meta\MetaCli\Core\MetaCli.Core.csproj" />
    <ProjectReference Include="..\Core\MetaDataQuality.Core.csproj" />
    <ProjectReference Include="..\Tooling\MetaDataQuality.Tooling.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="meta-data-quality.MetaCli\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
