// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaOrchestration
// Regenerate with:
//   meta generate csharp --workspace ".\MetaOrchestration" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaOrchestration
{
    public sealed class DependencyIssuePipeline
    {
        public string Id { get; set; } = string.Empty;

        public string Role { get; set; } = string.Empty;

        public DependencyIssue DependencyIssue { get; set; } = null!;

        public PipelineReference PipelineReference { get; set; } = null!;

    }
}
