// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaOrchestration
// Regenerate with:
//   meta generate csharp --workspace ".\MetaOrchestration" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaOrchestration
{
    public sealed class RetryPolicyFailureClass
    {
        public string Id { get; set; } = string.Empty;

        public string FailureClass { get; set; } = string.Empty;

        public string? Reason { get; set; }

        public string RetryBehavior { get; set; } = string.Empty;

        public RetryPolicy RetryPolicy { get; set; } = null!;

    }
}
