// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaOrchestration
// Regenerate with:
//   meta generate csharp --workspace ".\MetaOrchestration" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaOrchestration
{
    public sealed class TaskAccessProfile
    {
        public string Id { get; set; } = string.Empty;

        public string MetaPipelinePipelineTaskId { get; set; } = string.Empty;

        public string Ordinal { get; set; } = string.Empty;

        public string StatementKind { get; set; } = string.Empty;

        public string TaskName { get; set; } = string.Empty;

        public string TransformBindingId { get; set; } = string.Empty;

        public string TransformScriptId { get; set; } = string.Empty;

        public string TransformScriptName { get; set; } = string.Empty;

        public PipelineReference PipelineReference { get; set; } = null!;

    }
}
