// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaBusinessDataVault
// Regenerate with:
//   meta generate csharp --workspace ".\MetaBusinessDataVault" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaBusinessDataVault
{
    public sealed class BusinessBridgeHub
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("BusinessBridgeId")]
        public string BusinessBridgeId { get; set; } = string.Empty;

        [XmlAttribute("BusinessHubId")]
        public string BusinessHubId { get; set; } = string.Empty;

        [XmlElement("Ordinal")]
        public string Ordinal { get; set; } = string.Empty;

        [XmlElement("RoleName")]
        public string RoleName { get; set; } = string.Empty;
        public bool ShouldSerializeRoleName() => !string.IsNullOrWhiteSpace(RoleName);

        [XmlIgnore]
        public BusinessBridge BusinessBridge { get; set; } = null!;

        [XmlIgnore]
        public BusinessHub BusinessHub { get; set; } = null!;

    }
}
