// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaBusinessDataVault
// Regenerate with:
//   meta generate csharp --workspace ".\MetaBusinessDataVault" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaBusinessDataVault
{
    public sealed class BusinessPointInTimeLinkSatellite
    {
        public string Id { get; set; } = string.Empty;

        public string Ordinal { get; set; } = string.Empty;

        public BusinessLinkSatellite BusinessLinkSatellite { get; set; } = null!;

        public BusinessPointInTime BusinessPointInTime { get; set; } = null!;

    }
}
