// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaBusinessDataVault
// Regenerate with:
//   meta generate csharp --workspace ".\MetaBusinessDataVault" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaBusinessDataVault
{
    public sealed class BusinessPointInTimeLinkSatellite
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("BusinessLinkSatelliteId")]
        public string BusinessLinkSatelliteId { get; set; } = string.Empty;

        [XmlAttribute("BusinessPointInTimeId")]
        public string BusinessPointInTimeId { get; set; } = string.Empty;

        [XmlElement("Ordinal")]
        public string Ordinal { get; set; } = string.Empty;

        [XmlIgnore]
        public BusinessLinkSatellite BusinessLinkSatellite { get; set; } = null!;

        [XmlIgnore]
        public BusinessPointInTime BusinessPointInTime { get; set; } = null!;

    }
}
