// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaBusinessDataVault
// Regenerate with:
//   meta generate csharp --workspace ".\MetaBusinessDataVault" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaBusinessDataVault
{
    public sealed class BusinessHubSatelliteAttribute
    {
        public string Id { get; set; } = string.Empty;

        public string DataTypeId { get; set; } = string.Empty;

        public string Name { get; set; } = string.Empty;

        public BusinessHubSatellite BusinessHubSatellite { get; set; } = null!;

    }
}
