// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaPipeline
// Regenerate with:
//   meta generate csharp --workspace ".\MetaPipeline" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaPipeline
{
    public sealed class RowStream
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("PipelineId")]
        public string PipelineId { get; set; } = string.Empty;

        [XmlElement("Name")]
        public string Name { get; set; } = string.Empty;

        [XmlIgnore]
        public Pipeline Pipeline { get; set; } = null!;

    }
}
