// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaPipeline
// Regenerate with:
//   meta generate csharp --workspace ".\MetaPipeline" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaPipeline
{
    public sealed class RowStreamConsumer
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("PipelineTaskId")]
        public string PipelineTaskId { get; set; } = string.Empty;

        [XmlAttribute("RowStreamId")]
        public string RowStreamId { get; set; } = string.Empty;

        [XmlIgnore]
        public PipelineTask PipelineTask { get; set; } = null!;

        [XmlIgnore]
        public RowStream RowStream { get; set; } = null!;

    }
}
