<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meta.Core" Version="$(MetaFoundationPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MetaSchema\Core\MetaSchema.Core.csproj" />
    <ProjectReference Include="..\..\MetaDataVault\Core\MetaDataVault.Core.csproj" />
  </ItemGroup>

</Project>
