<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meta.Core" Version="$(MetaFoundationPackageVersion)" />
    <PackageReference Include="Meta.Integration" Version="$(MetaFoundationPackageVersion)" />
    <PackageReference Include="Meta.Operations" Version="$(MetaFoundationPackageVersion)" />
    <ProjectReference Include="..\..\MetaSql\CSharp\MetaSql.CSharp.csproj" />
    <ProjectReference Include="..\..\MetaTransform\Script\Sql\MetaTransformScript.Sql.csproj" />
  </ItemGroup>

</Project>
