@if exist "TransformWS" rmdir /s /q "TransformWS"
@if exist "DataQualityWS" rmdir /s /q "DataQualityWS"
@if exist "DataQualityWS_Supported" rmdir /s /q "DataQualityWS_Supported"
@if exist "BeforePromote.sql" del /q "BeforePromote.sql"
@if exist "Unsupported.sql" del /q "Unsupported.sql"
@if exist "AllPromoted.sql" del /q "AllPromoted.sql"
@if exist "DataQualityViews.sql" del /q "DataQualityViews.sql"
@if exist "before-promote.output" del /q "before-promote.output"
@if exist "unsupported.output" del /q "unsupported.output"
@if exist "implied-candidate-ids.txt" del /q "implied-candidate-ids.txt"
