IF DB_ID(N'$(DEMO_DB)') IS NOT NULL
BEGIN
    ALTER DATABASE [$(DEMO_DB)] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DEMO_DB)];
END
GO

IF DB_ID(N'$(METADQ_DB)') IS NOT NULL
BEGIN
    ALTER DATABASE [$(METADQ_DB)] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(METADQ_DB)];
END
GO
