// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaPipeline
// Regenerate with:
//   meta generate csharp --workspace ".\MetaPipeline" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaPipeline
{
    public sealed class InsertRowsTargetWriteTask
    {
        public string Id { get; set; } = string.Empty;

        public string? BatchSize { get; set; }

        public string? TargetDataTypeSystemName { get; set; }

        public string TargetSqlIdentifier { get; set; } = string.Empty;

        public TargetWriteTask TargetWriteTask { get; set; } = null!;

    }
}
