// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaPipeline
// Regenerate with:
//   meta generate csharp --workspace ".\MetaPipeline" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaPipeline
{
    public sealed class RowStreamColumn
    {
        public string Id { get; set; } = string.Empty;

        public string Name { get; set; } = string.Empty;

        public string Ordinal { get; set; } = string.Empty;

        public RowStream RowStream { get; set; } = null!;

    }
}
