// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\Workspace
// Regenerate with:
//   meta generate csharp --workspace ".\Workspace" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaDataTypeConversion
{
    public sealed class DataTypeMapping
    {
        public string Id { get; set; } = string.Empty;

        public string? Notes { get; set; }

        public string SourceDataTypeId { get; set; } = string.Empty;

        public string TargetDataTypeId { get; set; } = string.Empty;

        public ConversionImplementation ConversionImplementation { get; set; } = null!;

    }
}
