// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaSchema
// Regenerate with:
//   meta generate csharp --workspace ".\MetaSchema" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.Xml.Serialization;
using Meta.Core.Serialization;

namespace MetaSchema
{
    [XmlRoot("MetaSchema")]
    public sealed partial class MetaSchemaModel
    {
        public static MetaSchemaModel CreateEmpty() => new();

        [XmlArray("FieldList")]
        [XmlArrayItem("Field")]
        public List<Field> FieldList { get; set; } = new();
        public bool ShouldSerializeFieldList() => FieldList.Count > 0;

        [XmlArray("FieldDataTypeDetailList")]
        [XmlArrayItem("FieldDataTypeDetail")]
        public List<FieldDataTypeDetail> FieldDataTypeDetailList { get; set; } = new();
        public bool ShouldSerializeFieldDataTypeDetailList() => FieldDataTypeDetailList.Count > 0;

        [XmlArray("SchemaList")]
        [XmlArrayItem("Schema")]
        public List<Schema> SchemaList { get; set; } = new();
        public bool ShouldSerializeSchemaList() => SchemaList.Count > 0;

        [XmlArray("SystemList")]
        [XmlArrayItem("System")]
        public List<System> SystemList { get; set; } = new();
        public bool ShouldSerializeSystemList() => SystemList.Count > 0;

        [XmlArray("TableList")]
        [XmlArrayItem("Table")]
        public List<Table> TableList { get; set; } = new();
        public bool ShouldSerializeTableList() => TableList.Count > 0;

        [XmlArray("TableKeyList")]
        [XmlArrayItem("TableKey")]
        public List<TableKey> TableKeyList { get; set; } = new();
        public bool ShouldSerializeTableKeyList() => TableKeyList.Count > 0;

        [XmlArray("TableKeyFieldList")]
        [XmlArrayItem("TableKeyField")]
        public List<TableKeyField> TableKeyFieldList { get; set; } = new();
        public bool ShouldSerializeTableKeyFieldList() => TableKeyFieldList.Count > 0;

        [XmlArray("TableRelationshipList")]
        [XmlArrayItem("TableRelationship")]
        public List<TableRelationship> TableRelationshipList { get; set; } = new();
        public bool ShouldSerializeTableRelationshipList() => TableRelationshipList.Count > 0;

        [XmlArray("TableRelationshipFieldList")]
        [XmlArrayItem("TableRelationshipField")]
        public List<TableRelationshipField> TableRelationshipFieldList { get; set; } = new();
        public bool ShouldSerializeTableRelationshipFieldList() => TableRelationshipFieldList.Count > 0;

        public static MetaSchemaModel LoadFromXmlWorkspace(
            string workspacePath,
            bool searchUpward = true)
        {
            var model = TypedWorkspaceXmlSerializer.Load<MetaSchemaModel>(workspacePath, searchUpward);
            MetaSchemaModelFactory.Bind(model);
            return model;
        }

        public static Task<MetaSchemaModel> LoadFromXmlWorkspaceAsync(
            string workspacePath,
            bool searchUpward = true,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return Task.FromResult(LoadFromXmlWorkspace(workspacePath, searchUpward));
        }

        public void SaveToXmlWorkspace(string workspacePath)
        {
            MetaSchemaModelFactory.Bind(this);
            TypedWorkspaceXmlSerializer.Save(this, workspacePath, ResolveBundledModelXmlPath());
        }

        public Task SaveToXmlWorkspaceAsync(
            string workspacePath,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            SaveToXmlWorkspace(workspacePath);
            return Task.CompletedTask;
        }

        private static string? ResolveBundledModelXmlPath()
        {
            var assemblyDirectory = Path.GetDirectoryName(typeof(MetaSchemaModel).Assembly.Location);
            if (string.IsNullOrWhiteSpace(assemblyDirectory))
            {
                return null;
            }

            var directPath = Path.Combine(assemblyDirectory, "model.xml");
            if (File.Exists(directPath))
            {
                return directPath;
            }

            var namespacedPath = Path.Combine(assemblyDirectory, "MetaSchema", "model.xml");
            return File.Exists(namespacedPath) ? namespacedPath : null;
        }
    }

    internal static class MetaSchemaModelFactory
    {
        internal static void Bind(MetaSchemaModel model)
        {
            ArgumentNullException.ThrowIfNull(model);

            model.FieldList ??= new List<Field>();
            model.FieldDataTypeDetailList ??= new List<FieldDataTypeDetail>();
            model.SchemaList ??= new List<Schema>();
            model.SystemList ??= new List<System>();
            model.TableList ??= new List<Table>();
            model.TableKeyList ??= new List<TableKey>();
            model.TableKeyFieldList ??= new List<TableKeyField>();
            model.TableRelationshipList ??= new List<TableRelationship>();
            model.TableRelationshipFieldList ??= new List<TableRelationshipField>();

            NormalizeFieldList(model);
            NormalizeFieldDataTypeDetailList(model);
            NormalizeSchemaList(model);
            NormalizeSystemList(model);
            NormalizeTableList(model);
            NormalizeTableKeyList(model);
            NormalizeTableKeyFieldList(model);
            NormalizeTableRelationshipList(model);
            NormalizeTableRelationshipFieldList(model);

            var fieldListById = BuildById(model.FieldList, row => row.Id, "Field");
            var fieldDataTypeDetailListById = BuildById(model.FieldDataTypeDetailList, row => row.Id, "FieldDataTypeDetail");
            var schemaListById = BuildById(model.SchemaList, row => row.Id, "Schema");
            var systemListById = BuildById(model.SystemList, row => row.Id, "System");
            var tableListById = BuildById(model.TableList, row => row.Id, "Table");
            var tableKeyListById = BuildById(model.TableKeyList, row => row.Id, "TableKey");
            var tableKeyFieldListById = BuildById(model.TableKeyFieldList, row => row.Id, "TableKeyField");
            var tableRelationshipListById = BuildById(model.TableRelationshipList, row => row.Id, "TableRelationship");
            var tableRelationshipFieldListById = BuildById(model.TableRelationshipFieldList, row => row.Id, "TableRelationshipField");

            foreach (var row in model.FieldList)
            {
                row.TableId = ResolveRelationshipId(
                    row.TableId,
                    row.Table?.Id,
                    "Field",
                    row.Id,
                    "TableId");
                row.Table = RequireTarget(
                    tableListById,
                    row.TableId,
                    "Field",
                    row.Id,
                    "TableId");
            }

            foreach (var row in model.FieldDataTypeDetailList)
            {
                row.FieldId = ResolveRelationshipId(
                    row.FieldId,
                    row.Field?.Id,
                    "FieldDataTypeDetail",
                    row.Id,
                    "FieldId");
                row.Field = RequireTarget(
                    fieldListById,
                    row.FieldId,
                    "FieldDataTypeDetail",
                    row.Id,
                    "FieldId");
            }

            foreach (var row in model.SchemaList)
            {
                row.SystemId = ResolveRelationshipId(
                    row.SystemId,
                    row.System?.Id,
                    "Schema",
                    row.Id,
                    "SystemId");
                row.System = RequireTarget(
                    systemListById,
                    row.SystemId,
                    "Schema",
                    row.Id,
                    "SystemId");
            }

            foreach (var row in model.TableList)
            {
                row.SchemaId = ResolveRelationshipId(
                    row.SchemaId,
                    row.Schema?.Id,
                    "Table",
                    row.Id,
                    "SchemaId");
                row.Schema = RequireTarget(
                    schemaListById,
                    row.SchemaId,
                    "Table",
                    row.Id,
                    "SchemaId");
            }

            foreach (var row in model.TableKeyList)
            {
                row.TableId = ResolveRelationshipId(
                    row.TableId,
                    row.Table?.Id,
                    "TableKey",
                    row.Id,
                    "TableId");
                row.Table = RequireTarget(
                    tableListById,
                    row.TableId,
                    "TableKey",
                    row.Id,
                    "TableId");
            }

            foreach (var row in model.TableKeyFieldList)
            {
                row.FieldId = ResolveRelationshipId(
                    row.FieldId,
                    row.Field?.Id,
                    "TableKeyField",
                    row.Id,
                    "FieldId");
                row.Field = RequireTarget(
                    fieldListById,
                    row.FieldId,
                    "TableKeyField",
                    row.Id,
                    "FieldId");
            }

            foreach (var row in model.TableKeyFieldList)
            {
                row.TableKeyId = ResolveRelationshipId(
                    row.TableKeyId,
                    row.TableKey?.Id,
                    "TableKeyField",
                    row.Id,
                    "TableKeyId");
                row.TableKey = RequireTarget(
                    tableKeyListById,
                    row.TableKeyId,
                    "TableKeyField",
                    row.Id,
                    "TableKeyId");
            }

            foreach (var row in model.TableRelationshipList)
            {
                row.SourceTableId = ResolveRelationshipId(
                    row.SourceTableId,
                    row.SourceTable?.Id,
                    "TableRelationship",
                    row.Id,
                    "SourceTableId");
                row.SourceTable = RequireTarget(
                    tableListById,
                    row.SourceTableId,
                    "TableRelationship",
                    row.Id,
                    "SourceTableId");
            }

            foreach (var row in model.TableRelationshipList)
            {
                row.TargetTableId = ResolveRelationshipId(
                    row.TargetTableId,
                    row.TargetTable?.Id,
                    "TableRelationship",
                    row.Id,
                    "TargetTableId");
                row.TargetTable = RequireTarget(
                    tableListById,
                    row.TargetTableId,
                    "TableRelationship",
                    row.Id,
                    "TargetTableId");
            }

            foreach (var row in model.TableRelationshipFieldList)
            {
                row.SourceFieldId = ResolveRelationshipId(
                    row.SourceFieldId,
                    row.SourceField?.Id,
                    "TableRelationshipField",
                    row.Id,
                    "SourceFieldId");
                row.SourceField = RequireTarget(
                    fieldListById,
                    row.SourceFieldId,
                    "TableRelationshipField",
                    row.Id,
                    "SourceFieldId");
            }

            foreach (var row in model.TableRelationshipFieldList)
            {
                row.TableRelationshipId = ResolveRelationshipId(
                    row.TableRelationshipId,
                    row.TableRelationship?.Id,
                    "TableRelationshipField",
                    row.Id,
                    "TableRelationshipId");
                row.TableRelationship = RequireTarget(
                    tableRelationshipListById,
                    row.TableRelationshipId,
                    "TableRelationshipField",
                    row.Id,
                    "TableRelationshipId");
            }

            foreach (var row in model.TableRelationshipFieldList)
            {
                row.TargetFieldId = ResolveRelationshipId(
                    row.TargetFieldId,
                    row.TargetField?.Id,
                    "TableRelationshipField",
                    row.Id,
                    "TargetFieldId");
                row.TargetField = RequireTarget(
                    fieldListById,
                    row.TargetFieldId,
                    "TableRelationshipField",
                    row.Id,
                    "TargetFieldId");
            }

        }

        private static void NormalizeFieldList(MetaSchemaModel model)
        {
            foreach (var row in model.FieldList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'Field' contains a row with empty Id.");
                row.IdentityIncrement ??= string.Empty;
                row.IdentitySeed ??= string.Empty;
                row.IsIdentity ??= string.Empty;
                row.IsNullable ??= string.Empty;
                row.MetaDataTypeId = RequireText(row.MetaDataTypeId, $"Entity 'Field' row '{row.Id}' is missing required property 'MetaDataTypeId'.");
                row.Name = RequireText(row.Name, $"Entity 'Field' row '{row.Id}' is missing required property 'Name'.");
                row.Ordinal ??= string.Empty;
                row.TableId ??= string.Empty;
            }
        }

        private static void NormalizeFieldDataTypeDetailList(MetaSchemaModel model)
        {
            foreach (var row in model.FieldDataTypeDetailList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'FieldDataTypeDetail' contains a row with empty Id.");
                row.Name = RequireText(row.Name, $"Entity 'FieldDataTypeDetail' row '{row.Id}' is missing required property 'Name'.");
                row.Value = RequireText(row.Value, $"Entity 'FieldDataTypeDetail' row '{row.Id}' is missing required property 'Value'.");
                row.FieldId ??= string.Empty;
            }
        }

        private static void NormalizeSchemaList(MetaSchemaModel model)
        {
            foreach (var row in model.SchemaList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'Schema' contains a row with empty Id.");
                row.Name = RequireText(row.Name, $"Entity 'Schema' row '{row.Id}' is missing required property 'Name'.");
                row.SystemId ??= string.Empty;
            }
        }

        private static void NormalizeSystemList(MetaSchemaModel model)
        {
            foreach (var row in model.SystemList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'System' contains a row with empty Id.");
                row.Description ??= string.Empty;
                row.Name = RequireText(row.Name, $"Entity 'System' row '{row.Id}' is missing required property 'Name'.");
            }
        }

        private static void NormalizeTableList(MetaSchemaModel model)
        {
            foreach (var row in model.TableList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'Table' contains a row with empty Id.");
                row.Name = RequireText(row.Name, $"Entity 'Table' row '{row.Id}' is missing required property 'Name'.");
                row.ObjectType ??= string.Empty;
                row.SchemaId ??= string.Empty;
            }
        }

        private static void NormalizeTableKeyList(MetaSchemaModel model)
        {
            foreach (var row in model.TableKeyList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'TableKey' contains a row with empty Id.");
                row.KeyType = RequireText(row.KeyType, $"Entity 'TableKey' row '{row.Id}' is missing required property 'KeyType'.");
                row.Name = RequireText(row.Name, $"Entity 'TableKey' row '{row.Id}' is missing required property 'Name'.");
                row.TableId ??= string.Empty;
            }
        }

        private static void NormalizeTableKeyFieldList(MetaSchemaModel model)
        {
            foreach (var row in model.TableKeyFieldList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'TableKeyField' contains a row with empty Id.");
                row.FieldName = RequireText(row.FieldName, $"Entity 'TableKeyField' row '{row.Id}' is missing required property 'FieldName'.");
                row.Ordinal = RequireText(row.Ordinal, $"Entity 'TableKeyField' row '{row.Id}' is missing required property 'Ordinal'.");
                row.FieldId ??= string.Empty;
                row.TableKeyId ??= string.Empty;
            }
        }

        private static void NormalizeTableRelationshipList(MetaSchemaModel model)
        {
            foreach (var row in model.TableRelationshipList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'TableRelationship' contains a row with empty Id.");
                row.Name = RequireText(row.Name, $"Entity 'TableRelationship' row '{row.Id}' is missing required property 'Name'.");
                row.SourceTableId ??= string.Empty;
                row.TargetTableId ??= string.Empty;
            }
        }

        private static void NormalizeTableRelationshipFieldList(MetaSchemaModel model)
        {
            foreach (var row in model.TableRelationshipFieldList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'TableRelationshipField' contains a row with empty Id.");
                row.Ordinal = RequireText(row.Ordinal, $"Entity 'TableRelationshipField' row '{row.Id}' is missing required property 'Ordinal'.");
                row.SourceFieldId ??= string.Empty;
                row.TableRelationshipId ??= string.Empty;
                row.TargetFieldId ??= string.Empty;
            }
        }

        private static Dictionary<string, T> BuildById<T>(
            IEnumerable<T> rows,
            Func<T, string> getId,
            string entityName)
            where T : class
        {
            var rowsById = new Dictionary<string, T>(StringComparer.Ordinal);
            foreach (var row in rows)
            {
                ArgumentNullException.ThrowIfNull(row);
                var id = RequireIdentity(getId(row), $"Entity '{entityName}' contains a row with empty Id.");
                if (!rowsById.TryAdd(id, row))
                {
                    throw new InvalidOperationException($"Entity '{entityName}' contains duplicate Id '{id}'.");
                }
            }

            return rowsById;
        }

        private static T RequireTarget<T>(
            Dictionary<string, T> rowsById,
            string targetId,
            string sourceEntityName,
            string sourceId,
            string relationshipName)
            where T : class
        {
            var normalizedTargetId = RequireIdentity(targetId, $"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' is empty.");
            if (!rowsById.TryGetValue(normalizedTargetId, out var target))
            {
                throw new InvalidOperationException($"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' points to missing Id '{normalizedTargetId}'.");
            }

            return target;
        }

        private static string ResolveRelationshipId(
            string relationshipId,
            string? navigationId,
            string sourceEntityName,
            string sourceId,
            string relationshipName)
        {
            var normalizedRelationshipId = NormalizeIdentity(relationshipId);
            var normalizedNavigationId = NormalizeIdentity(navigationId);
            if (!string.IsNullOrEmpty(normalizedRelationshipId) &&
                !string.IsNullOrEmpty(normalizedNavigationId) &&
                !string.Equals(normalizedRelationshipId, normalizedNavigationId, StringComparison.Ordinal))
            {
                throw new InvalidOperationException($"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' conflicts between '{normalizedRelationshipId}' and '{normalizedNavigationId}'.");
            }

            var resolvedTargetId = string.IsNullOrEmpty(normalizedRelationshipId)
                ? normalizedNavigationId
                : normalizedRelationshipId;
            return RequireIdentity(resolvedTargetId, $"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' is empty.");
        }

        private static string RequireIdentity(string? value, string errorMessage)
        {
            var normalizedValue = NormalizeIdentity(value);
            if (string.IsNullOrEmpty(normalizedValue))
            {
                throw new InvalidOperationException(errorMessage);
            }

            return normalizedValue;
        }

        private static string RequireText(string? value, string errorMessage)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new InvalidOperationException(errorMessage);
            }

            return value;
        }

        private static string NormalizeIdentity(string? value)
        {
            return string.IsNullOrWhiteSpace(value)
                ? string.Empty
                : value.Trim();
        }
    }
}
