// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaSchema
// Regenerate with:
//   meta generate csharp --workspace ".\MetaSchema" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaSchema
{
    public sealed class System
    {
        public string Id { get; set; } = string.Empty;

        public string? Description { get; set; }

        public string Name { get; set; } = string.Empty;

    }
}
