// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaSchema
// Regenerate with:
//   meta generate csharp --workspace ".\MetaSchema" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaSchema
{
    public sealed class TableRelationship
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("SourceTableId")]
        public string SourceTableId { get; set; } = string.Empty;

        [XmlAttribute("TargetTableId")]
        public string TargetTableId { get; set; } = string.Empty;

        [XmlElement("Name")]
        public string Name { get; set; } = string.Empty;

        [XmlIgnore]
        public Table SourceTable { get; set; } = null!;

        [XmlIgnore]
        public Table TargetTable { get; set; } = null!;

    }
}
