<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meta.Core" Version="$(MetaFoundationPackageVersion)" />
    <PackageReference Include="Microsoft.AnalysisServices.NetCore.retail.amd64" Version="19.84.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tooling\MetaTabular.Tooling.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\Workspaces\MetaTabular\model.xml">
      <Link>Models\MetaTabular.model.xml</Link>
      <LogicalName>MetaTabular.Core.Models.MetaTabular.model.xml</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
