// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaMultiDimensional
// Regenerate with:
//   meta generate csharp --workspace ".\MetaMultiDimensional" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaMultiDimensional
{
    public sealed class DimensionUsage
    {
        public string Id { get; set; } = string.Empty;

        public string? Description { get; set; }

        public string? IsRequired { get; set; }

        public string? RoleName { get; set; }

        public string UsageKind { get; set; } = string.Empty;

        public CubeDimension CubeDimension { get; set; } = null!;

        public DimensionAttribute? GranularityAttribute { get; set; }

        public MeasureGroup? IntermediateMeasureGroup { get; set; }

        public MeasureGroup MeasureGroup { get; set; } = null!;

    }
}
