// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaMultiDimensional
// Regenerate with:
//   meta generate csharp --workspace ".\MetaMultiDimensional" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System.Threading;
using System.Threading.Tasks;

namespace MetaMultiDimensional
{
    public static class MetaMultiDimensionalTooling
    {
        public static MetaMultiDimensionalModel Load(
            string workspacePath,
            bool searchUpward = true)
        {
            return MetaMultiDimensionalModel.LoadFromXmlWorkspace(workspacePath, searchUpward);
        }

        public static Task<MetaMultiDimensionalModel> LoadAsync(
            string workspacePath,
            bool searchUpward = true,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return MetaMultiDimensionalModel.LoadFromXmlWorkspaceAsync(workspacePath, searchUpward, cancellationToken);
        }

        public static void Save(MetaMultiDimensionalModel model, string workspacePath)
        {
            if (model == null)
            {
                throw new global::System.ArgumentNullException(nameof(model));
            }

            model.SaveToXmlWorkspace(workspacePath);
        }

        public static Task SaveAsync(MetaMultiDimensionalModel model, string workspacePath,
            CancellationToken cancellationToken = default)
        {
            if (model == null)
            {
                throw new global::System.ArgumentNullException(nameof(model));
            }

            cancellationToken.ThrowIfCancellationRequested();
            model.SaveToXmlWorkspace(workspacePath);
            return Task.CompletedTask;
        }
    }
}
