// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaMultiDimensional
// Regenerate with:
//   meta generate csharp --workspace ".\MetaMultiDimensional" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaMultiDimensional
{
    public sealed class Partition
    {
        public string Id { get; set; } = string.Empty;

        public string? Description { get; set; }

        public string Name { get; set; } = string.Empty;

        public string Ordinal { get; set; } = string.Empty;

        public string? ProcessingMode { get; set; }

        public string? SliceExpression { get; set; }

        public string? SourceExpression { get; set; }

        public string? StorageMode { get; set; }

        public MeasureGroup MeasureGroup { get; set; } = null!;

        public MultiDimensionalDataSource? MultiDimensionalDataSource { get; set; }

    }
}
