<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meta.Integration" Version="$(MetaFoundationPackageVersion)" />
    <PackageReference Include="Meta.Operations" Version="$(MetaFoundationPackageVersion)" />
    <PackageReference Include="MetaWeave.Core" Version="$(MetaFoundationPackageVersion)" />
    <ProjectReference Include="..\..\MetaDataQuality\Core\MetaDataQuality.Core.csproj" />
    <ProjectReference Include="..\..\MetaSql\CSharp\MetaSql.CSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Weaves\DataQualityToSql\**\*">
      <Link>Weaves\DataQualityToSql\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>true</Pack>
      <PackagePath>contentFiles\any\any\Weaves\DataQualityToSql\%(RecursiveDir)%(Filename)%(Extension)</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
    <EmbeddedResource Include="MetaDQ.Operational.sql">
      <LogicalName>MetaConvert.DataQualityToSql.MetaDQ.Operational.sql</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
