// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformBinding
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformBinding" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformBinding
{
    public sealed class BoundColumnReference
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("OwnerId")]
        public string OwnerId { get; set; } = string.Empty;

        [XmlAttribute("ResolvedTableSourceId")]
        public string ResolvedTableSourceId { get; set; } = string.Empty;

        [XmlAttribute("ValueId")]
        public string ValueId { get; set; } = string.Empty;

        [XmlElement("SyntaxColumnReferenceId")]
        public string SyntaxColumnReferenceId { get; set; } = string.Empty;

        [XmlIgnore]
        public TransformBinding Owner { get; set; } = null!;

        [XmlIgnore]
        public BoundTableSource ResolvedTableSource { get; set; } = null!;

        [XmlIgnore]
        public BoundColumn Value { get; set; } = null!;

    }
}
