// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformBinding
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformBinding" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformBinding
{
    public sealed class BoundColumn
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("OwnerId")]
        public string OwnerId { get; set; } = string.Empty;

        [XmlElement("Name")]
        public string Name { get; set; } = string.Empty;

        [XmlElement("Ordinal")]
        public string Ordinal { get; set; } = string.Empty;

        [XmlElement("SourceFieldId")]
        public string SourceFieldId { get; set; } = string.Empty;
        public bool ShouldSerializeSourceFieldId() => !string.IsNullOrWhiteSpace(SourceFieldId);

        [XmlElement("SourceTableId")]
        public string SourceTableId { get; set; } = string.Empty;
        public bool ShouldSerializeSourceTableId() => !string.IsNullOrWhiteSpace(SourceTableId);

        [XmlIgnore]
        public BoundRowset Owner { get; set; } = null!;

    }
}
