// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformBinding
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformBinding" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformBinding
{
    public sealed class BoundRowset
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("OwnerId")]
        public string OwnerId { get; set; } = string.Empty;

        [XmlElement("DerivationKind")]
        public string DerivationKind { get; set; } = string.Empty;

        [XmlElement("Name")]
        public string Name { get; set; } = string.Empty;

        [XmlElement("RowsetRole")]
        public string RowsetRole { get; set; } = string.Empty;
        public bool ShouldSerializeRowsetRole() => !string.IsNullOrWhiteSpace(RowsetRole);

        [XmlElement("SourceTableId")]
        public string SourceTableId { get; set; } = string.Empty;
        public bool ShouldSerializeSourceTableId() => !string.IsNullOrWhiteSpace(SourceTableId);

        [XmlElement("SyntaxId")]
        public string SyntaxId { get; set; } = string.Empty;
        public bool ShouldSerializeSyntaxId() => !string.IsNullOrWhiteSpace(SyntaxId);

        [XmlIgnore]
        public TransformBinding Owner { get; set; } = null!;

    }
}
