// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformBinding
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformBinding" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformBinding
{
    public sealed class Issue
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("TransformBindingId")]
        public string TransformBindingId { get; set; } = string.Empty;

        [XmlElement("Code")]
        public string Code { get; set; } = string.Empty;

        [XmlElement("Message")]
        public string Message { get; set; } = string.Empty;

        [XmlElement("Severity")]
        public string Severity { get; set; } = string.Empty;
        public bool ShouldSerializeSeverity() => !string.IsNullOrWhiteSpace(Severity);

        [XmlElement("SyntaxId")]
        public string SyntaxId { get; set; } = string.Empty;
        public bool ShouldSerializeSyntaxId() => !string.IsNullOrWhiteSpace(SyntaxId);

        [XmlIgnore]
        public TransformBinding TransformBinding { get; set; } = null!;

    }
}
