// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformBinding
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformBinding" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.Xml.Serialization;
using Meta.Core.Serialization;

namespace MetaTransformBinding
{
    [XmlRoot("MetaTransformBinding")]
    public sealed partial class MetaTransformBindingModel
    {
        public static MetaTransformBindingModel CreateEmpty() => new();

        [XmlArray("ColumnList")]
        [XmlArrayItem("Column")]
        public List<Column> ColumnList { get; set; } = new();
        public bool ShouldSerializeColumnList() => ColumnList.Count > 0;

        [XmlArray("ColumnReferenceList")]
        [XmlArrayItem("ColumnReference")]
        public List<ColumnReference> ColumnReferenceList { get; set; } = new();
        public bool ShouldSerializeColumnReferenceList() => ColumnReferenceList.Count > 0;

        [XmlArray("IssueList")]
        [XmlArrayItem("Issue")]
        public List<Issue> IssueList { get; set; } = new();
        public bool ShouldSerializeIssueList() => IssueList.Count > 0;

        [XmlArray("OutputRowsetList")]
        [XmlArrayItem("OutputRowset")]
        public List<OutputRowset> OutputRowsetList { get; set; } = new();
        public bool ShouldSerializeOutputRowsetList() => OutputRowsetList.Count > 0;

        [XmlArray("RowsetList")]
        [XmlArrayItem("Rowset")]
        public List<Rowset> RowsetList { get; set; } = new();
        public bool ShouldSerializeRowsetList() => RowsetList.Count > 0;

        [XmlArray("RowsetSourceValidationList")]
        [XmlArrayItem("RowsetSourceValidation")]
        public List<RowsetSourceValidation> RowsetSourceValidationList { get; set; } = new();
        public bool ShouldSerializeRowsetSourceValidationList() => RowsetSourceValidationList.Count > 0;

        [XmlArray("RowsetTargetValidationList")]
        [XmlArrayItem("RowsetTargetValidation")]
        public List<RowsetTargetValidation> RowsetTargetValidationList { get; set; } = new();
        public bool ShouldSerializeRowsetTargetValidationList() => RowsetTargetValidationList.Count > 0;

        [XmlArray("SourceTargetList")]
        [XmlArrayItem("SourceTarget")]
        public List<SourceTarget> SourceTargetList { get; set; } = new();
        public bool ShouldSerializeSourceTargetList() => SourceTargetList.Count > 0;

        [XmlArray("TableSourceList")]
        [XmlArrayItem("TableSource")]
        public List<TableSource> TableSourceList { get; set; } = new();
        public bool ShouldSerializeTableSourceList() => TableSourceList.Count > 0;

        [XmlArray("TransformBindingList")]
        [XmlArrayItem("TransformBinding")]
        public List<TransformBinding> TransformBindingList { get; set; } = new();
        public bool ShouldSerializeTransformBindingList() => TransformBindingList.Count > 0;

        [XmlArray("TransformBindingTargetList")]
        [XmlArrayItem("TransformBindingTarget")]
        public List<TransformBindingTarget> TransformBindingTargetList { get; set; } = new();
        public bool ShouldSerializeTransformBindingTargetList() => TransformBindingTargetList.Count > 0;

        [XmlArray("TransformBindingValidationList")]
        [XmlArrayItem("TransformBindingValidation")]
        public List<TransformBindingValidation> TransformBindingValidationList { get; set; } = new();
        public bool ShouldSerializeTransformBindingValidationList() => TransformBindingValidationList.Count > 0;

        [XmlArray("TransformBindingValidationIssueList")]
        [XmlArrayItem("TransformBindingValidationIssue")]
        public List<TransformBindingValidationIssue> TransformBindingValidationIssueList { get; set; } = new();
        public bool ShouldSerializeTransformBindingValidationIssueList() => TransformBindingValidationIssueList.Count > 0;

        public static MetaTransformBindingModel LoadFromXmlWorkspace(
            string workspacePath,
            bool searchUpward = true)
        {
            var model = TypedWorkspaceXmlSerializer.Load<MetaTransformBindingModel>(workspacePath, searchUpward);
            MetaTransformBindingModelFactory.Bind(model);
            return model;
        }

        public static Task<MetaTransformBindingModel> LoadFromXmlWorkspaceAsync(
            string workspacePath,
            bool searchUpward = true,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return Task.FromResult(LoadFromXmlWorkspace(workspacePath, searchUpward));
        }

        public void SaveToXmlWorkspace(string workspacePath)
        {
            MetaTransformBindingModelFactory.Bind(this);
            TypedWorkspaceXmlSerializer.Save(this, workspacePath, ResolveBundledModelXmlPath());
        }

        public Task SaveToXmlWorkspaceAsync(
            string workspacePath,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            SaveToXmlWorkspace(workspacePath);
            return Task.CompletedTask;
        }

        private static string? ResolveBundledModelXmlPath()
        {
            var assemblyDirectory = Path.GetDirectoryName(typeof(MetaTransformBindingModel).Assembly.Location);
            if (string.IsNullOrWhiteSpace(assemblyDirectory))
            {
                return null;
            }

            var directPath = Path.Combine(assemblyDirectory, "model.xml");
            if (File.Exists(directPath))
            {
                return directPath;
            }

            var namespacedPath = Path.Combine(assemblyDirectory, "MetaTransformBinding", "model.xml");
            return File.Exists(namespacedPath) ? namespacedPath : null;
        }
    }

    internal static class MetaTransformBindingModelFactory
    {
        internal static void Bind(MetaTransformBindingModel model)
        {
            ArgumentNullException.ThrowIfNull(model);

            model.ColumnList ??= new List<Column>();
            model.ColumnReferenceList ??= new List<ColumnReference>();
            model.IssueList ??= new List<Issue>();
            model.OutputRowsetList ??= new List<OutputRowset>();
            model.RowsetList ??= new List<Rowset>();
            model.RowsetSourceValidationList ??= new List<RowsetSourceValidation>();
            model.RowsetTargetValidationList ??= new List<RowsetTargetValidation>();
            model.SourceTargetList ??= new List<SourceTarget>();
            model.TableSourceList ??= new List<TableSource>();
            model.TransformBindingList ??= new List<TransformBinding>();
            model.TransformBindingTargetList ??= new List<TransformBindingTarget>();
            model.TransformBindingValidationList ??= new List<TransformBindingValidation>();
            model.TransformBindingValidationIssueList ??= new List<TransformBindingValidationIssue>();

            NormalizeColumnList(model);
            NormalizeColumnReferenceList(model);
            NormalizeIssueList(model);
            NormalizeOutputRowsetList(model);
            NormalizeRowsetList(model);
            NormalizeRowsetSourceValidationList(model);
            NormalizeRowsetTargetValidationList(model);
            NormalizeSourceTargetList(model);
            NormalizeTableSourceList(model);
            NormalizeTransformBindingList(model);
            NormalizeTransformBindingTargetList(model);
            NormalizeTransformBindingValidationList(model);
            NormalizeTransformBindingValidationIssueList(model);

            var columnListById = BuildById(model.ColumnList, row => row.Id, "Column");
            var columnReferenceListById = BuildById(model.ColumnReferenceList, row => row.Id, "ColumnReference");
            var issueListById = BuildById(model.IssueList, row => row.Id, "Issue");
            var outputRowsetListById = BuildById(model.OutputRowsetList, row => row.Id, "OutputRowset");
            var rowsetListById = BuildById(model.RowsetList, row => row.Id, "Rowset");
            var rowsetSourceValidationListById = BuildById(model.RowsetSourceValidationList, row => row.Id, "RowsetSourceValidation");
            var rowsetTargetValidationListById = BuildById(model.RowsetTargetValidationList, row => row.Id, "RowsetTargetValidation");
            var sourceTargetListById = BuildById(model.SourceTargetList, row => row.Id, "SourceTarget");
            var tableSourceListById = BuildById(model.TableSourceList, row => row.Id, "TableSource");
            var transformBindingListById = BuildById(model.TransformBindingList, row => row.Id, "TransformBinding");
            var transformBindingTargetListById = BuildById(model.TransformBindingTargetList, row => row.Id, "TransformBindingTarget");
            var transformBindingValidationListById = BuildById(model.TransformBindingValidationList, row => row.Id, "TransformBindingValidation");
            var transformBindingValidationIssueListById = BuildById(model.TransformBindingValidationIssueList, row => row.Id, "TransformBindingValidationIssue");

            foreach (var row in model.ColumnList)
            {
                row.RowsetId = ResolveRelationshipId(
                    row.RowsetId,
                    row.Rowset?.Id,
                    "Column",
                    row.Id,
                    "RowsetId");
                row.Rowset = RequireTarget(
                    rowsetListById,
                    row.RowsetId,
                    "Column",
                    row.Id,
                    "RowsetId");
            }

            foreach (var row in model.ColumnReferenceList)
            {
                row.ColumnId = ResolveRelationshipId(
                    row.ColumnId,
                    row.Column?.Id,
                    "ColumnReference",
                    row.Id,
                    "ColumnId");
                row.Column = RequireTarget(
                    columnListById,
                    row.ColumnId,
                    "ColumnReference",
                    row.Id,
                    "ColumnId");
            }

            foreach (var row in model.ColumnReferenceList)
            {
                row.TableSourceId = ResolveRelationshipId(
                    row.TableSourceId,
                    row.TableSource?.Id,
                    "ColumnReference",
                    row.Id,
                    "TableSourceId");
                row.TableSource = RequireTarget(
                    tableSourceListById,
                    row.TableSourceId,
                    "ColumnReference",
                    row.Id,
                    "TableSourceId");
            }

            foreach (var row in model.ColumnReferenceList)
            {
                row.TransformBindingId = ResolveRelationshipId(
                    row.TransformBindingId,
                    row.TransformBinding?.Id,
                    "ColumnReference",
                    row.Id,
                    "TransformBindingId");
                row.TransformBinding = RequireTarget(
                    transformBindingListById,
                    row.TransformBindingId,
                    "ColumnReference",
                    row.Id,
                    "TransformBindingId");
            }

            foreach (var row in model.IssueList)
            {
                row.TransformBindingId = ResolveRelationshipId(
                    row.TransformBindingId,
                    row.TransformBinding?.Id,
                    "Issue",
                    row.Id,
                    "TransformBindingId");
                row.TransformBinding = RequireTarget(
                    transformBindingListById,
                    row.TransformBindingId,
                    "Issue",
                    row.Id,
                    "TransformBindingId");
            }

            foreach (var row in model.OutputRowsetList)
            {
                row.RowsetId = ResolveRelationshipId(
                    row.RowsetId,
                    row.Rowset?.Id,
                    "OutputRowset",
                    row.Id,
                    "RowsetId");
                row.Rowset = RequireTarget(
                    rowsetListById,
                    row.RowsetId,
                    "OutputRowset",
                    row.Id,
                    "RowsetId");
            }

            foreach (var row in model.OutputRowsetList)
            {
                row.TransformBindingId = ResolveRelationshipId(
                    row.TransformBindingId,
                    row.TransformBinding?.Id,
                    "OutputRowset",
                    row.Id,
                    "TransformBindingId");
                row.TransformBinding = RequireTarget(
                    transformBindingListById,
                    row.TransformBindingId,
                    "OutputRowset",
                    row.Id,
                    "TransformBindingId");
            }

            foreach (var row in model.RowsetList)
            {
                row.TransformBindingId = ResolveRelationshipId(
                    row.TransformBindingId,
                    row.TransformBinding?.Id,
                    "Rowset",
                    row.Id,
                    "TransformBindingId");
                row.TransformBinding = RequireTarget(
                    transformBindingListById,
                    row.TransformBindingId,
                    "Rowset",
                    row.Id,
                    "TransformBindingId");
            }

            foreach (var row in model.RowsetSourceValidationList)
            {
                row.RowsetId = ResolveRelationshipId(
                    row.RowsetId,
                    row.Rowset?.Id,
                    "RowsetSourceValidation",
                    row.Id,
                    "RowsetId");
                row.Rowset = RequireTarget(
                    rowsetListById,
                    row.RowsetId,
                    "RowsetSourceValidation",
                    row.Id,
                    "RowsetId");
            }

            foreach (var row in model.RowsetSourceValidationList)
            {
                row.TransformBindingValidationId = ResolveRelationshipId(
                    row.TransformBindingValidationId,
                    row.TransformBindingValidation?.Id,
                    "RowsetSourceValidation",
                    row.Id,
                    "TransformBindingValidationId");
                row.TransformBindingValidation = RequireTarget(
                    transformBindingValidationListById,
                    row.TransformBindingValidationId,
                    "RowsetSourceValidation",
                    row.Id,
                    "TransformBindingValidationId");
            }

            foreach (var row in model.RowsetTargetValidationList)
            {
                row.RowsetId = ResolveRelationshipId(
                    row.RowsetId,
                    row.Rowset?.Id,
                    "RowsetTargetValidation",
                    row.Id,
                    "RowsetId");
                row.Rowset = RequireTarget(
                    rowsetListById,
                    row.RowsetId,
                    "RowsetTargetValidation",
                    row.Id,
                    "RowsetId");
            }

            foreach (var row in model.RowsetTargetValidationList)
            {
                row.TransformBindingValidationId = ResolveRelationshipId(
                    row.TransformBindingValidationId,
                    row.TransformBindingValidation?.Id,
                    "RowsetTargetValidation",
                    row.Id,
                    "TransformBindingValidationId");
                row.TransformBindingValidation = RequireTarget(
                    transformBindingValidationListById,
                    row.TransformBindingValidationId,
                    "RowsetTargetValidation",
                    row.Id,
                    "TransformBindingValidationId");
            }

            foreach (var row in model.SourceTargetList)
            {
                row.SourceId = ResolveRelationshipId(
                    row.SourceId,
                    row.Source?.Id,
                    "SourceTarget",
                    row.Id,
                    "SourceId");
                row.Source = RequireTarget(
                    rowsetListById,
                    row.SourceId,
                    "SourceTarget",
                    row.Id,
                    "SourceId");
            }

            foreach (var row in model.SourceTargetList)
            {
                row.TargetId = ResolveRelationshipId(
                    row.TargetId,
                    row.Target?.Id,
                    "SourceTarget",
                    row.Id,
                    "TargetId");
                row.Target = RequireTarget(
                    rowsetListById,
                    row.TargetId,
                    "SourceTarget",
                    row.Id,
                    "TargetId");
            }

            foreach (var row in model.TableSourceList)
            {
                row.RowsetId = ResolveRelationshipId(
                    row.RowsetId,
                    row.Rowset?.Id,
                    "TableSource",
                    row.Id,
                    "RowsetId");
                row.Rowset = RequireTarget(
                    rowsetListById,
                    row.RowsetId,
                    "TableSource",
                    row.Id,
                    "RowsetId");
            }

            foreach (var row in model.TableSourceList)
            {
                row.TransformBindingId = ResolveRelationshipId(
                    row.TransformBindingId,
                    row.TransformBinding?.Id,
                    "TableSource",
                    row.Id,
                    "TransformBindingId");
                row.TransformBinding = RequireTarget(
                    transformBindingListById,
                    row.TransformBindingId,
                    "TableSource",
                    row.Id,
                    "TransformBindingId");
            }

            foreach (var row in model.TransformBindingTargetList)
            {
                row.TransformBindingId = ResolveRelationshipId(
                    row.TransformBindingId,
                    row.TransformBinding?.Id,
                    "TransformBindingTarget",
                    row.Id,
                    "TransformBindingId");
                row.TransformBinding = RequireTarget(
                    transformBindingListById,
                    row.TransformBindingId,
                    "TransformBindingTarget",
                    row.Id,
                    "TransformBindingId");
            }

            foreach (var row in model.TransformBindingValidationList)
            {
                row.TransformBindingId = ResolveRelationshipId(
                    row.TransformBindingId,
                    row.TransformBinding?.Id,
                    "TransformBindingValidation",
                    row.Id,
                    "TransformBindingId");
                row.TransformBinding = RequireTarget(
                    transformBindingListById,
                    row.TransformBindingId,
                    "TransformBindingValidation",
                    row.Id,
                    "TransformBindingId");
            }

            foreach (var row in model.TransformBindingValidationIssueList)
            {
                row.TransformBindingValidationId = ResolveRelationshipId(
                    row.TransformBindingValidationId,
                    row.TransformBindingValidation?.Id,
                    "TransformBindingValidationIssue",
                    row.Id,
                    "TransformBindingValidationId");
                row.TransformBindingValidation = RequireTarget(
                    transformBindingValidationListById,
                    row.TransformBindingValidationId,
                    "TransformBindingValidationIssue",
                    row.Id,
                    "TransformBindingValidationId");
            }

        }

        private static void NormalizeColumnList(MetaTransformBindingModel model)
        {
            foreach (var row in model.ColumnList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'Column' contains a row with empty Id.");
                row.Name = RequireText(row.Name, $"Entity 'Column' row '{row.Id}' is missing required property 'Name'.");
                row.Ordinal = RequireText(row.Ordinal, $"Entity 'Column' row '{row.Id}' is missing required property 'Ordinal'.");
                row.RowsetId ??= string.Empty;
            }
        }

        private static void NormalizeColumnReferenceList(MetaTransformBindingModel model)
        {
            foreach (var row in model.ColumnReferenceList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'ColumnReference' contains a row with empty Id.");
                row.SyntaxColumnReferenceId = RequireText(row.SyntaxColumnReferenceId, $"Entity 'ColumnReference' row '{row.Id}' is missing required property 'SyntaxColumnReferenceId'.");
                row.ColumnId ??= string.Empty;
                row.TableSourceId ??= string.Empty;
                row.TransformBindingId ??= string.Empty;
            }
        }

        private static void NormalizeIssueList(MetaTransformBindingModel model)
        {
            foreach (var row in model.IssueList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'Issue' contains a row with empty Id.");
                row.Code = RequireText(row.Code, $"Entity 'Issue' row '{row.Id}' is missing required property 'Code'.");
                row.Message = RequireText(row.Message, $"Entity 'Issue' row '{row.Id}' is missing required property 'Message'.");
                row.Severity ??= string.Empty;
                row.SyntaxId ??= string.Empty;
                row.TransformBindingId ??= string.Empty;
            }
        }

        private static void NormalizeOutputRowsetList(MetaTransformBindingModel model)
        {
            foreach (var row in model.OutputRowsetList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'OutputRowset' contains a row with empty Id.");
                row.RowsetId ??= string.Empty;
                row.TransformBindingId ??= string.Empty;
            }
        }

        private static void NormalizeRowsetList(MetaTransformBindingModel model)
        {
            foreach (var row in model.RowsetList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'Rowset' contains a row with empty Id.");
                row.DerivationKind = RequireText(row.DerivationKind, $"Entity 'Rowset' row '{row.Id}' is missing required property 'DerivationKind'.");
                row.Name = RequireText(row.Name, $"Entity 'Rowset' row '{row.Id}' is missing required property 'Name'.");
                row.RowsetRole ??= string.Empty;
                row.SqlIdentifier ??= string.Empty;
                row.SyntaxId ??= string.Empty;
                row.TransformBindingId ??= string.Empty;
            }
        }

        private static void NormalizeRowsetSourceValidationList(MetaTransformBindingModel model)
        {
            foreach (var row in model.RowsetSourceValidationList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'RowsetSourceValidation' contains a row with empty Id.");
                row.ConformanceKind = RequireText(row.ConformanceKind, $"Entity 'RowsetSourceValidation' row '{row.Id}' is missing required property 'ConformanceKind'.");
                row.ResolutionKind = RequireText(row.ResolutionKind, $"Entity 'RowsetSourceValidation' row '{row.Id}' is missing required property 'ResolutionKind'.");
                row.TableId ??= string.Empty;
                row.RowsetId ??= string.Empty;
                row.TransformBindingValidationId ??= string.Empty;
            }
        }

        private static void NormalizeRowsetTargetValidationList(MetaTransformBindingModel model)
        {
            foreach (var row in model.RowsetTargetValidationList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'RowsetTargetValidation' contains a row with empty Id.");
                row.ConformanceKind = RequireText(row.ConformanceKind, $"Entity 'RowsetTargetValidation' row '{row.Id}' is missing required property 'ConformanceKind'.");
                row.ResolutionKind = RequireText(row.ResolutionKind, $"Entity 'RowsetTargetValidation' row '{row.Id}' is missing required property 'ResolutionKind'.");
                row.SqlIdentifier = RequireText(row.SqlIdentifier, $"Entity 'RowsetTargetValidation' row '{row.Id}' is missing required property 'SqlIdentifier'.");
                row.TableId ??= string.Empty;
                row.RowsetId ??= string.Empty;
                row.TransformBindingValidationId ??= string.Empty;
            }
        }

        private static void NormalizeSourceTargetList(MetaTransformBindingModel model)
        {
            foreach (var row in model.SourceTargetList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'SourceTarget' contains a row with empty Id.");
                row.InputRole ??= string.Empty;
                row.Ordinal = RequireText(row.Ordinal, $"Entity 'SourceTarget' row '{row.Id}' is missing required property 'Ordinal'.");
                row.SourceId ??= string.Empty;
                row.TargetId ??= string.Empty;
            }
        }

        private static void NormalizeTableSourceList(MetaTransformBindingModel model)
        {
            foreach (var row in model.TableSourceList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'TableSource' contains a row with empty Id.");
                row.ExposedName = RequireText(row.ExposedName, $"Entity 'TableSource' row '{row.Id}' is missing required property 'ExposedName'.");
                row.SyntaxTableReferenceId = RequireText(row.SyntaxTableReferenceId, $"Entity 'TableSource' row '{row.Id}' is missing required property 'SyntaxTableReferenceId'.");
                row.RowsetId ??= string.Empty;
                row.TransformBindingId ??= string.Empty;
            }
        }

        private static void NormalizeTransformBindingList(MetaTransformBindingModel model)
        {
            foreach (var row in model.TransformBindingList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'TransformBinding' contains a row with empty Id.");
                row.ActiveLanguageProfileId = RequireText(row.ActiveLanguageProfileId, $"Entity 'TransformBinding' row '{row.Id}' is missing required property 'ActiveLanguageProfileId'.");
                row.TransformScriptId = RequireText(row.TransformScriptId, $"Entity 'TransformBinding' row '{row.Id}' is missing required property 'TransformScriptId'.");
                row.TransformScriptName ??= string.Empty;
            }
        }

        private static void NormalizeTransformBindingTargetList(MetaTransformBindingModel model)
        {
            foreach (var row in model.TransformBindingTargetList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'TransformBindingTarget' contains a row with empty Id.");
                row.SqlIdentifier = RequireText(row.SqlIdentifier, $"Entity 'TransformBindingTarget' row '{row.Id}' is missing required property 'SqlIdentifier'.");
                row.TransformBindingId ??= string.Empty;
            }
        }

        private static void NormalizeTransformBindingValidationList(MetaTransformBindingModel model)
        {
            foreach (var row in model.TransformBindingValidationList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'TransformBindingValidation' contains a row with empty Id.");
                row.TransformBindingId ??= string.Empty;
            }
        }

        private static void NormalizeTransformBindingValidationIssueList(MetaTransformBindingModel model)
        {
            foreach (var row in model.TransformBindingValidationIssueList)
            {
                ArgumentNullException.ThrowIfNull(row);
                row.Id = RequireIdentity(row.Id, "Entity 'TransformBindingValidationIssue' contains a row with empty Id.");
                row.Code = RequireText(row.Code, $"Entity 'TransformBindingValidationIssue' row '{row.Id}' is missing required property 'Code'.");
                row.Message = RequireText(row.Message, $"Entity 'TransformBindingValidationIssue' row '{row.Id}' is missing required property 'Message'.");
                row.Severity ??= string.Empty;
                row.SyntaxId ??= string.Empty;
                row.TransformBindingValidationId ??= string.Empty;
            }
        }

        private static Dictionary<string, T> BuildById<T>(
            IEnumerable<T> rows,
            Func<T, string> getId,
            string entityName)
            where T : class
        {
            var rowsById = new Dictionary<string, T>(StringComparer.Ordinal);
            foreach (var row in rows)
            {
                ArgumentNullException.ThrowIfNull(row);
                var id = RequireIdentity(getId(row), $"Entity '{entityName}' contains a row with empty Id.");
                if (!rowsById.TryAdd(id, row))
                {
                    throw new InvalidOperationException($"Entity '{entityName}' contains duplicate Id '{id}'.");
                }
            }

            return rowsById;
        }

        private static T RequireTarget<T>(
            Dictionary<string, T> rowsById,
            string targetId,
            string sourceEntityName,
            string sourceId,
            string relationshipName)
            where T : class
        {
            var normalizedTargetId = RequireIdentity(targetId, $"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' is empty.");
            if (!rowsById.TryGetValue(normalizedTargetId, out var target))
            {
                throw new InvalidOperationException($"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' points to missing Id '{normalizedTargetId}'.");
            }

            return target;
        }

        private static string ResolveRelationshipId(
            string relationshipId,
            string? navigationId,
            string sourceEntityName,
            string sourceId,
            string relationshipName)
        {
            var normalizedRelationshipId = NormalizeIdentity(relationshipId);
            var normalizedNavigationId = NormalizeIdentity(navigationId);
            if (!string.IsNullOrEmpty(normalizedRelationshipId) &&
                !string.IsNullOrEmpty(normalizedNavigationId) &&
                !string.Equals(normalizedRelationshipId, normalizedNavigationId, StringComparison.Ordinal))
            {
                throw new InvalidOperationException($"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' conflicts between '{normalizedRelationshipId}' and '{normalizedNavigationId}'.");
            }

            var resolvedTargetId = string.IsNullOrEmpty(normalizedRelationshipId)
                ? normalizedNavigationId
                : normalizedRelationshipId;
            return RequireIdentity(resolvedTargetId, $"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' is empty.");
        }

        private static string RequireIdentity(string? value, string errorMessage)
        {
            var normalizedValue = NormalizeIdentity(value);
            if (string.IsNullOrEmpty(normalizedValue))
            {
                throw new InvalidOperationException(errorMessage);
            }

            return normalizedValue;
        }

        private static string RequireText(string? value, string errorMessage)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new InvalidOperationException(errorMessage);
            }

            return value;
        }

        private static string NormalizeIdentity(string? value)
        {
            return string.IsNullOrWhiteSpace(value)
                ? string.Empty
                : value.Trim();
        }
    }
}
