// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformBinding
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformBinding" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformBinding
{
    public sealed class RowsetSourceValidation
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("RowsetId")]
        public string RowsetId { get; set; } = string.Empty;

        [XmlAttribute("TransformBindingValidationId")]
        public string TransformBindingValidationId { get; set; } = string.Empty;

        [XmlElement("ConformanceKind")]
        public string ConformanceKind { get; set; } = string.Empty;

        [XmlElement("ResolutionKind")]
        public string ResolutionKind { get; set; } = string.Empty;

        [XmlElement("TableId")]
        public string TableId { get; set; } = string.Empty;
        public bool ShouldSerializeTableId() => !string.IsNullOrWhiteSpace(TableId);

        [XmlIgnore]
        public Rowset Rowset { get; set; } = null!;

        [XmlIgnore]
        public TransformBindingValidation TransformBindingValidation { get; set; } = null!;

    }
}
