// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformBinding
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformBinding" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformBinding
{
    public sealed class SourceTarget
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("SourceId")]
        public string SourceId { get; set; } = string.Empty;

        [XmlAttribute("TargetId")]
        public string TargetId { get; set; } = string.Empty;

        [XmlElement("InputRole")]
        public string InputRole { get; set; } = string.Empty;
        public bool ShouldSerializeInputRole() => !string.IsNullOrWhiteSpace(InputRole);

        [XmlElement("Ordinal")]
        public string Ordinal { get; set; } = string.Empty;

        [XmlIgnore]
        public Rowset Source { get; set; } = null!;

        [XmlIgnore]
        public Rowset Target { get; set; } = null!;

    }
}
