// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformBinding
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformBinding" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaTransformBinding
{
    public sealed class SourceTarget
    {
        public string Id { get; set; } = string.Empty;

        public string? InputRole { get; set; }

        public string Ordinal { get; set; } = string.Empty;

        public Rowset Source { get; set; } = null!;

        public Rowset Target { get; set; } = null!;

    }
}
