// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformBinding
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformBinding" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformBinding
{
    public sealed class TransformBindingSource
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("TransformBindingId")]
        public string TransformBindingId { get; set; } = string.Empty;

        [XmlElement("SqlIdentifier")]
        public string SqlIdentifier { get; set; } = string.Empty;

        [XmlElement("TableId")]
        public string TableId { get; set; } = string.Empty;

        [XmlIgnore]
        public TransformBinding TransformBinding { get; set; } = null!;

    }
}
