// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformBinding
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformBinding" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformBinding
{
    public sealed class TransformBinding
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlElement("ActiveLanguageProfileId")]
        public string ActiveLanguageProfileId { get; set; } = string.Empty;

        [XmlElement("TransformScriptId")]
        public string TransformScriptId { get; set; } = string.Empty;

        [XmlElement("TransformScriptName")]
        public string TransformScriptName { get; set; } = string.Empty;
        public bool ShouldSerializeTransformScriptName() => !string.IsNullOrWhiteSpace(TransformScriptName);

    }
}
