// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformBinding
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformBinding" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformBinding
{
    public sealed class ValidationSourceColumnLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("ColumnId")]
        public string ColumnId { get; set; } = string.Empty;

        [XmlAttribute("ValidationSourceRowsetLinkId")]
        public string ValidationSourceRowsetLinkId { get; set; } = string.Empty;

        [XmlElement("MetaSchemaFieldId")]
        public string MetaSchemaFieldId { get; set; } = string.Empty;

        [XmlIgnore]
        public Column Column { get; set; } = null!;

        [XmlIgnore]
        public ValidationSourceRowsetLink ValidationSourceRowsetLink { get; set; } = null!;

    }
}
