// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformBinding
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformBinding" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaTransformBinding
{
    public sealed class ValidationTargetColumnLink
    {
        public string Id { get; set; } = string.Empty;

        public string MetaSchemaFieldId { get; set; } = string.Empty;

        public Column Column { get; set; } = null!;

        public ValidationTargetRowsetLink ValidationTargetRowsetLink { get; set; } = null!;

    }
}
