// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformBinding
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformBinding" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformBinding
{
    public sealed class ValidationSourceRowsetLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("RowsetId")]
        public string RowsetId { get; set; } = string.Empty;

        [XmlAttribute("ValidationId")]
        public string ValidationId { get; set; } = string.Empty;

        [XmlElement("MetaSchemaTableId")]
        public string MetaSchemaTableId { get; set; } = string.Empty;

        [XmlIgnore]
        public Rowset Rowset { get; set; } = null!;

        [XmlIgnore]
        public Validation Validation { get; set; } = null!;

    }
}
