// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformBinding
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformBinding" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaTransformBinding
{
    public sealed class ValidationTargetColumnTypeSanctionedConversion
    {
        public string Id { get; set; } = string.Empty;

        public string SourceMetaDataTypeId { get; set; } = string.Empty;

        public string TargetMetaDataTypeId { get; set; } = string.Empty;

        public ValidationTargetColumnLink ValidationTargetColumnLink { get; set; } = null!;

    }
}
