// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaDataWarehouse
// Regenerate with:
//   meta generate csharp --workspace ".\MetaDataWarehouse" --out <dir> --tooling
// </auto-generated>

#nullable enable

using Meta.Core.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace MetaDataWarehouse
{
    public static class MetaDataWarehouseTooling
    {
        public static MetaDataWarehouseModel Load(
            string workspacePath,
            bool searchUpward = false)
        {
            return MetaDataWarehouseModel.LoadFromXmlWorkspace(workspacePath, searchUpward);
        }

        public static Task<MetaDataWarehouseModel> LoadAsync(
            string workspacePath,
            bool searchUpward = false,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return MetaDataWarehouseModel.LoadFromXmlWorkspaceAsync(workspacePath, searchUpward, cancellationToken);
        }

        public static string CreateWorkspace(string workspacePath)
        {
            return TypedWorkspaceXmlSerializer.CreateWorkspace<MetaDataWarehouseModel>(workspacePath);
        }

        public static bool IsWorkspace(string workspacePath)
        {
            return TypedWorkspaceXmlSerializer.IsWorkspace<MetaDataWarehouseModel>(workspacePath);
        }

        public static void Save(MetaDataWarehouseModel model, string workspacePath)
        {
            if (model == null)
            {
                throw new global::System.ArgumentNullException(nameof(model));
            }

            model.SaveToXmlWorkspace(workspacePath);
        }

        public static Task SaveAsync(MetaDataWarehouseModel model, string workspacePath,
            CancellationToken cancellationToken = default)
        {
            if (model == null)
            {
                throw new global::System.ArgumentNullException(nameof(model));
            }

            cancellationToken.ThrowIfCancellationRequested();
            model.SaveToXmlWorkspace(workspacePath);
            return Task.CompletedTask;
        }
    }
}
