// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class BinaryExpression
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("ScalarExpressionId")]
        public string ScalarExpressionId { get; set; } = string.Empty;

        [XmlElement("BinaryExpressionType")]
        public string BinaryExpressionType { get; set; } = string.Empty;
        public bool ShouldSerializeBinaryExpressionType() => !string.IsNullOrWhiteSpace(BinaryExpressionType);

        [XmlIgnore]
        public ScalarExpression ScalarExpression { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string BaseId { get => ScalarExpressionId; set => ScalarExpressionId = value; }

        [XmlIgnore]
        public ScalarExpression Base { get => ScalarExpression; set => ScalarExpression = value; }

    }
}
