// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class BinaryLiteral
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("LiteralId")]
        public string LiteralId { get; set; } = string.Empty;

        [XmlElement("IsLargeObject")]
        public string IsLargeObject { get; set; } = string.Empty;
        public bool ShouldSerializeIsLargeObject() => !string.IsNullOrWhiteSpace(IsLargeObject);

        [XmlElement("LiteralType")]
        public string LiteralType { get; set; } = string.Empty;
        public bool ShouldSerializeLiteralType() => !string.IsNullOrWhiteSpace(LiteralType);

        [XmlIgnore]
        public Literal Literal { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string BaseId { get => LiteralId; set => LiteralId = value; }

        [XmlIgnore]
        public Literal Base { get => Literal; set => Literal = value; }

    }
}
