// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class BooleanParenthesisExpressionExpressionLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("BooleanExpressionId")]
        public string BooleanExpressionId { get; set; } = string.Empty;

        [XmlAttribute("BooleanParenthesisExpressionId")]
        public string BooleanParenthesisExpressionId { get; set; } = string.Empty;

        [XmlIgnore]
        public BooleanExpression BooleanExpression { get; set; } = null!;

        [XmlIgnore]
        public BooleanParenthesisExpression BooleanParenthesisExpression { get; set; } = null!;

    }
}
