// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class CastCallParameterLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("CastCallId")]
        public string CastCallId { get; set; } = string.Empty;

        [XmlAttribute("ScalarExpressionId")]
        public string ScalarExpressionId { get; set; } = string.Empty;

        [XmlIgnore]
        public CastCall CastCall { get; set; } = null!;

        [XmlIgnore]
        public ScalarExpression ScalarExpression { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => CastCallId; set => CastCallId = value; }

        [XmlIgnore]
        public CastCall Owner { get => CastCall; set => CastCall = value; }

        [XmlIgnore]
        public string ValueId { get => ScalarExpressionId; set => ScalarExpressionId = value; }

        [XmlIgnore]
        public ScalarExpression Value { get => ScalarExpression; set => ScalarExpression = value; }

    }
}
