// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class CommonTableExpressionQueryExpressionLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("CommonTableExpressionId")]
        public string CommonTableExpressionId { get; set; } = string.Empty;

        [XmlAttribute("QueryExpressionId")]
        public string QueryExpressionId { get; set; } = string.Empty;

        [XmlIgnore]
        public CommonTableExpression CommonTableExpression { get; set; } = null!;

        [XmlIgnore]
        public QueryExpression QueryExpression { get; set; } = null!;

    }
}
