// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class ConvertCallStyleLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("ConvertCallId")]
        public string ConvertCallId { get; set; } = string.Empty;

        [XmlAttribute("ScalarExpressionId")]
        public string ScalarExpressionId { get; set; } = string.Empty;

        [XmlIgnore]
        public ConvertCall ConvertCall { get; set; } = null!;

        [XmlIgnore]
        public ScalarExpression ScalarExpression { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => ConvertCallId; set => ConvertCallId = value; }

        [XmlIgnore]
        public ConvertCall Owner { get => ConvertCall; set => ConvertCall = value; }

        [XmlIgnore]
        public string ValueId { get => ScalarExpressionId; set => ScalarExpressionId = value; }

        [XmlIgnore]
        public ScalarExpression Value { get => ScalarExpression; set => ScalarExpression = value; }

    }
}
