// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class ConvertCallDataTypeLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("ConvertCallId")]
        public string ConvertCallId { get; set; } = string.Empty;

        [XmlAttribute("DataTypeReferenceId")]
        public string DataTypeReferenceId { get; set; } = string.Empty;

        [XmlIgnore]
        public ConvertCall ConvertCall { get; set; } = null!;

        [XmlIgnore]
        public DataTypeReference DataTypeReference { get; set; } = null!;

    }
}
