// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class ExistsPredicateSubqueryLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("ExistsPredicateId")]
        public string ExistsPredicateId { get; set; } = string.Empty;

        [XmlAttribute("ScalarSubqueryId")]
        public string ScalarSubqueryId { get; set; } = string.Empty;

        [XmlIgnore]
        public ExistsPredicate ExistsPredicate { get; set; } = null!;

        [XmlIgnore]
        public ScalarSubquery ScalarSubquery { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => ExistsPredicateId; set => ExistsPredicateId = value; }

        [XmlIgnore]
        public ExistsPredicate Owner { get => ExistsPredicate; set => ExistsPredicate = value; }

        [XmlIgnore]
        public string ValueId { get => ScalarSubqueryId; set => ScalarSubqueryId = value; }

        [XmlIgnore]
        public ScalarSubquery Value { get => ScalarSubquery; set => ScalarSubquery = value; }

    }
}
