// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class FullTextPredicateValueLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("FullTextPredicateId")]
        public string FullTextPredicateId { get; set; } = string.Empty;

        [XmlAttribute("ValueExpressionId")]
        public string ValueExpressionId { get; set; } = string.Empty;

        [XmlIgnore]
        public FullTextPredicate FullTextPredicate { get; set; } = null!;

        [XmlIgnore]
        public ValueExpression ValueExpression { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => FullTextPredicateId; set => FullTextPredicateId = value; }

        [XmlIgnore]
        public FullTextPredicate Owner { get => FullTextPredicate; set => FullTextPredicate = value; }

        [XmlIgnore]
        public string ValueId { get => ValueExpressionId; set => ValueExpressionId = value; }

        [XmlIgnore]
        public ValueExpression Value { get => ValueExpression; set => ValueExpression = value; }

    }
}
