// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class FullTextTableReferenceColumnsItem
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("ColumnReferenceExpressionId")]
        public string ColumnReferenceExpressionId { get; set; } = string.Empty;

        [XmlAttribute("FullTextTableReferenceId")]
        public string FullTextTableReferenceId { get; set; } = string.Empty;

        [XmlElement("Ordinal")]
        public string Ordinal { get; set; } = string.Empty;
        public bool ShouldSerializeOrdinal() => !string.IsNullOrWhiteSpace(Ordinal);

        [XmlIgnore]
        public ColumnReferenceExpression ColumnReferenceExpression { get; set; } = null!;

        [XmlIgnore]
        public FullTextTableReference FullTextTableReference { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => FullTextTableReferenceId; set => FullTextTableReferenceId = value; }

        [XmlIgnore]
        public FullTextTableReference Owner { get => FullTextTableReference; set => FullTextTableReference = value; }

        [XmlIgnore]
        public string ValueId { get => ColumnReferenceExpressionId; set => ColumnReferenceExpressionId = value; }

        [XmlIgnore]
        public ColumnReferenceExpression Value { get => ColumnReferenceExpression; set => ColumnReferenceExpression = value; }

    }
}
