// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaTransformScript
{
    public sealed class FullTextTableReferenceColumnsItem
    {
        public string Id { get; set; } = string.Empty;

        public string? Ordinal { get; set; }

        public ColumnReferenceExpression ColumnReferenceExpression { get; set; } = null!;

        public FullTextTableReference FullTextTableReference { get; set; } = null!;

    }
}
