// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class FullTextTableReferenceSearchConditionLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("FullTextTableReferenceId")]
        public string FullTextTableReferenceId { get; set; } = string.Empty;

        [XmlAttribute("ValueExpressionId")]
        public string ValueExpressionId { get; set; } = string.Empty;

        [XmlIgnore]
        public FullTextTableReference FullTextTableReference { get; set; } = null!;

        [XmlIgnore]
        public ValueExpression ValueExpression { get; set; } = null!;

    }
}
