// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaTransformScript
{
    public sealed class FunctionCall
    {
        public string Id { get; set; } = string.Empty;

        public string? UniqueRowFilter { get; set; }

        public string? WithArrayWrapper { get; set; }

        public PrimaryExpression PrimaryExpression { get; set; } = null!;

    }
}
