// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class GlobalFunctionTableReferenceNameLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("GlobalFunctionTableReferenceId")]
        public string GlobalFunctionTableReferenceId { get; set; } = string.Empty;

        [XmlAttribute("IdentifierId")]
        public string IdentifierId { get; set; } = string.Empty;

        [XmlIgnore]
        public GlobalFunctionTableReference GlobalFunctionTableReference { get; set; } = null!;

        [XmlIgnore]
        public Identifier Identifier { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => GlobalFunctionTableReferenceId; set => GlobalFunctionTableReferenceId = value; }

        [XmlIgnore]
        public GlobalFunctionTableReference Owner { get => GlobalFunctionTableReference; set => GlobalFunctionTableReference = value; }

        [XmlIgnore]
        public string ValueId { get => IdentifierId; set => IdentifierId = value; }

        [XmlIgnore]
        public Identifier Value { get => Identifier; set => Identifier = value; }

    }
}
