// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class GroupByClauseGroupingSpecificationsItem
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("GroupByClauseId")]
        public string GroupByClauseId { get; set; } = string.Empty;

        [XmlAttribute("GroupingSpecificationId")]
        public string GroupingSpecificationId { get; set; } = string.Empty;

        [XmlElement("Ordinal")]
        public string Ordinal { get; set; } = string.Empty;
        public bool ShouldSerializeOrdinal() => !string.IsNullOrWhiteSpace(Ordinal);

        [XmlIgnore]
        public GroupByClause GroupByClause { get; set; } = null!;

        [XmlIgnore]
        public GroupingSpecification GroupingSpecification { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => GroupByClauseId; set => GroupByClauseId = value; }

        [XmlIgnore]
        public GroupByClause Owner { get => GroupByClause; set => GroupByClause = value; }

        [XmlIgnore]
        public string ValueId { get => GroupingSpecificationId; set => GroupingSpecificationId = value; }

        [XmlIgnore]
        public GroupingSpecification Value { get => GroupingSpecification; set => GroupingSpecification = value; }

    }
}
