// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class GroupingSetsGroupingSpecificationSetsItem
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("GroupingSetsGroupingSpecificationId")]
        public string GroupingSetsGroupingSpecificationId { get; set; } = string.Empty;

        [XmlAttribute("GroupingSpecificationId")]
        public string GroupingSpecificationId { get; set; } = string.Empty;

        [XmlElement("Ordinal")]
        public string Ordinal { get; set; } = string.Empty;
        public bool ShouldSerializeOrdinal() => !string.IsNullOrWhiteSpace(Ordinal);

        [XmlIgnore]
        public GroupingSetsGroupingSpecification GroupingSetsGroupingSpecification { get; set; } = null!;

        [XmlIgnore]
        public GroupingSpecification GroupingSpecification { get; set; } = null!;

    }
}
