// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class HavingClauseSearchConditionLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("BooleanExpressionId")]
        public string BooleanExpressionId { get; set; } = string.Empty;

        [XmlAttribute("HavingClauseId")]
        public string HavingClauseId { get; set; } = string.Empty;

        [XmlIgnore]
        public BooleanExpression BooleanExpression { get; set; } = null!;

        [XmlIgnore]
        public HavingClause HavingClause { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => HavingClauseId; set => HavingClauseId = value; }

        [XmlIgnore]
        public HavingClause Owner { get => HavingClause; set => HavingClause = value; }

        [XmlIgnore]
        public string ValueId { get => BooleanExpressionId; set => BooleanExpressionId = value; }

        [XmlIgnore]
        public BooleanExpression Value { get => BooleanExpression; set => BooleanExpression = value; }

    }
}
