// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class InlineDerivedTableRowValuesItem
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("InlineDerivedTableId")]
        public string InlineDerivedTableId { get; set; } = string.Empty;

        [XmlAttribute("RowValueId")]
        public string RowValueId { get; set; } = string.Empty;

        [XmlElement("Ordinal")]
        public string Ordinal { get; set; } = string.Empty;
        public bool ShouldSerializeOrdinal() => !string.IsNullOrWhiteSpace(Ordinal);

        [XmlIgnore]
        public InlineDerivedTable InlineDerivedTable { get; set; } = null!;

        [XmlIgnore]
        public RowValue RowValue { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => InlineDerivedTableId; set => InlineDerivedTableId = value; }

        [XmlIgnore]
        public InlineDerivedTable Owner { get => InlineDerivedTable; set => InlineDerivedTable = value; }

        [XmlIgnore]
        public string ValueId { get => RowValueId; set => RowValueId = value; }

        [XmlIgnore]
        public RowValue Value { get => RowValue; set => RowValue = value; }

    }
}
