// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class InPredicateSubqueryLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("InPredicateId")]
        public string InPredicateId { get; set; } = string.Empty;

        [XmlAttribute("ScalarSubqueryId")]
        public string ScalarSubqueryId { get; set; } = string.Empty;

        [XmlIgnore]
        public InPredicate InPredicate { get; set; } = null!;

        [XmlIgnore]
        public ScalarSubquery ScalarSubquery { get; set; } = null!;

    }
}
