// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class InPredicate
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("BooleanExpressionId")]
        public string BooleanExpressionId { get; set; } = string.Empty;

        [XmlElement("NotDefined")]
        public string NotDefined { get; set; } = string.Empty;
        public bool ShouldSerializeNotDefined() => !string.IsNullOrWhiteSpace(NotDefined);

        [XmlIgnore]
        public BooleanExpression BooleanExpression { get; set; } = null!;

    }
}
