// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class JoinParenthesisTableReferenceJoinLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("JoinParenthesisTableReferenceId")]
        public string JoinParenthesisTableReferenceId { get; set; } = string.Empty;

        [XmlAttribute("TableReferenceId")]
        public string TableReferenceId { get; set; } = string.Empty;

        [XmlIgnore]
        public JoinParenthesisTableReference JoinParenthesisTableReference { get; set; } = null!;

        [XmlIgnore]
        public TableReference TableReference { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => JoinParenthesisTableReferenceId; set => JoinParenthesisTableReferenceId = value; }

        [XmlIgnore]
        public JoinParenthesisTableReference Owner { get => JoinParenthesisTableReference; set => JoinParenthesisTableReference = value; }

        [XmlIgnore]
        public string ValueId { get => TableReferenceId; set => TableReferenceId = value; }

        [XmlIgnore]
        public TableReference Value { get => TableReference; set => TableReference = value; }

    }
}
