// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class LeftFunctionCallParametersItem
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("LeftFunctionCallId")]
        public string LeftFunctionCallId { get; set; } = string.Empty;

        [XmlAttribute("ScalarExpressionId")]
        public string ScalarExpressionId { get; set; } = string.Empty;

        [XmlElement("Ordinal")]
        public string Ordinal { get; set; } = string.Empty;
        public bool ShouldSerializeOrdinal() => !string.IsNullOrWhiteSpace(Ordinal);

        [XmlIgnore]
        public LeftFunctionCall LeftFunctionCall { get; set; } = null!;

        [XmlIgnore]
        public ScalarExpression ScalarExpression { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => LeftFunctionCallId; set => LeftFunctionCallId = value; }

        [XmlIgnore]
        public LeftFunctionCall Owner { get => LeftFunctionCall; set => LeftFunctionCall = value; }

        [XmlIgnore]
        public string ValueId { get => ScalarExpressionId; set => ScalarExpressionId = value; }

        [XmlIgnore]
        public ScalarExpression Value { get => ScalarExpression; set => ScalarExpression = value; }

    }
}
