// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class Literal
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("ValueExpressionId")]
        public string ValueExpressionId { get; set; } = string.Empty;

        [XmlElement("LiteralType")]
        public string LiteralType { get; set; } = string.Empty;
        public bool ShouldSerializeLiteralType() => !string.IsNullOrWhiteSpace(LiteralType);

        [XmlElement("Value")]
        public string Value { get; set; } = string.Empty;
        public bool ShouldSerializeValue() => !string.IsNullOrWhiteSpace(Value);

        [XmlIgnore]
        public ValueExpression ValueExpression { get; set; } = null!;

    }
}
