// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using Meta.Core.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace MetaTransformScript
{
    public static class MetaTransformScriptTooling
    {
        public static MetaTransformScriptModel Load(
            string workspacePath,
            bool searchUpward = false)
        {
            return MetaTransformScriptModel.LoadFromXmlWorkspace(workspacePath, searchUpward);
        }

        public static Task<MetaTransformScriptModel> LoadAsync(
            string workspacePath,
            bool searchUpward = false,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return MetaTransformScriptModel.LoadFromXmlWorkspaceAsync(workspacePath, searchUpward, cancellationToken);
        }

        public static string CreateWorkspace(string workspacePath)
        {
            return TypedWorkspaceXmlSerializer.CreateWorkspace<MetaTransformScriptModel>(workspacePath);
        }

        public static bool IsWorkspace(string workspacePath)
        {
            return TypedWorkspaceXmlSerializer.IsWorkspace<MetaTransformScriptModel>(workspacePath);
        }

        public static void Save(MetaTransformScriptModel model, string workspacePath)
        {
            if (model == null)
            {
                throw new global::System.ArgumentNullException(nameof(model));
            }

            model.SaveToXmlWorkspace(workspacePath);
        }

        public static Task SaveAsync(MetaTransformScriptModel model, string workspacePath,
            CancellationToken cancellationToken = default)
        {
            if (model == null)
            {
                throw new global::System.ArgumentNullException(nameof(model));
            }

            cancellationToken.ThrowIfCancellationRequested();
            model.SaveToXmlWorkspace(workspacePath);
            return Task.CompletedTask;
        }
    }
}
