// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class MultiPartIdentifierCallTargetMultiPartIdentifierLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("MultiPartIdentifierCallTargetId")]
        public string MultiPartIdentifierCallTargetId { get; set; } = string.Empty;

        [XmlAttribute("MultiPartIdentifierId")]
        public string MultiPartIdentifierId { get; set; } = string.Empty;

        [XmlIgnore]
        public MultiPartIdentifierCallTarget MultiPartIdentifierCallTarget { get; set; } = null!;

        [XmlIgnore]
        public MultiPartIdentifier MultiPartIdentifier { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => MultiPartIdentifierCallTargetId; set => MultiPartIdentifierCallTargetId = value; }

        [XmlIgnore]
        public MultiPartIdentifierCallTarget Owner { get => MultiPartIdentifierCallTarget; set => MultiPartIdentifierCallTarget = value; }

        [XmlIgnore]
        public string ValueId { get => MultiPartIdentifierId; set => MultiPartIdentifierId = value; }

        [XmlIgnore]
        public MultiPartIdentifier Value { get => MultiPartIdentifier; set => MultiPartIdentifier = value; }

    }
}
