// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class NamedTableReferenceSchemaObjectLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("NamedTableReferenceId")]
        public string NamedTableReferenceId { get; set; } = string.Empty;

        [XmlAttribute("SchemaObjectNameId")]
        public string SchemaObjectNameId { get; set; } = string.Empty;

        [XmlIgnore]
        public NamedTableReference NamedTableReference { get; set; } = null!;

        [XmlIgnore]
        public SchemaObjectName SchemaObjectName { get; set; } = null!;

    }
}
