// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class NamedTableReference
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("TableReferenceWithAliasId")]
        public string TableReferenceWithAliasId { get; set; } = string.Empty;

        [XmlIgnore]
        public TableReferenceWithAlias TableReferenceWithAlias { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string BaseId { get => TableReferenceWithAliasId; set => TableReferenceWithAliasId = value; }

        [XmlIgnore]
        public TableReferenceWithAlias Base { get => TableReferenceWithAlias; set => TableReferenceWithAlias = value; }

    }
}
