// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class NextValueForExpressionSequenceNameLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("NextValueForExpressionId")]
        public string NextValueForExpressionId { get; set; } = string.Empty;

        [XmlAttribute("SchemaObjectNameId")]
        public string SchemaObjectNameId { get; set; } = string.Empty;

        [XmlIgnore]
        public NextValueForExpression NextValueForExpression { get; set; } = null!;

        [XmlIgnore]
        public SchemaObjectName SchemaObjectName { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => NextValueForExpressionId; set => NextValueForExpressionId = value; }

        [XmlIgnore]
        public NextValueForExpression Owner { get => NextValueForExpression; set => NextValueForExpression = value; }

        [XmlIgnore]
        public string ValueId { get => SchemaObjectNameId; set => SchemaObjectNameId = value; }

        [XmlIgnore]
        public SchemaObjectName Value { get => SchemaObjectName; set => SchemaObjectName = value; }

    }
}
