// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class OrderByClauseOrderByElementsItem
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("ExpressionWithSortOrderId")]
        public string ExpressionWithSortOrderId { get; set; } = string.Empty;

        [XmlAttribute("OrderByClauseId")]
        public string OrderByClauseId { get; set; } = string.Empty;

        [XmlElement("Ordinal")]
        public string Ordinal { get; set; } = string.Empty;
        public bool ShouldSerializeOrdinal() => !string.IsNullOrWhiteSpace(Ordinal);

        [XmlIgnore]
        public ExpressionWithSortOrder ExpressionWithSortOrder { get; set; } = null!;

        [XmlIgnore]
        public OrderByClause OrderByClause { get; set; } = null!;

    }
}
