// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class OverClauseWindowFrameClauseLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("OverClauseId")]
        public string OverClauseId { get; set; } = string.Empty;

        [XmlAttribute("WindowFrameClauseId")]
        public string WindowFrameClauseId { get; set; } = string.Empty;

        [XmlIgnore]
        public OverClause OverClause { get; set; } = null!;

        [XmlIgnore]
        public WindowFrameClause WindowFrameClause { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => OverClauseId; set => OverClauseId = value; }

        [XmlIgnore]
        public OverClause Owner { get => OverClause; set => OverClause = value; }

        [XmlIgnore]
        public string ValueId { get => WindowFrameClauseId; set => WindowFrameClauseId = value; }

        [XmlIgnore]
        public WindowFrameClause Value { get => WindowFrameClause; set => WindowFrameClause = value; }

    }
}
