// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class ParameterlessCall
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("PrimaryExpressionId")]
        public string PrimaryExpressionId { get; set; } = string.Empty;

        [XmlElement("ParameterlessCallType")]
        public string ParameterlessCallType { get; set; } = string.Empty;
        public bool ShouldSerializeParameterlessCallType() => !string.IsNullOrWhiteSpace(ParameterlessCallType);

        [XmlIgnore]
        public PrimaryExpression PrimaryExpression { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string BaseId { get => PrimaryExpressionId; set => PrimaryExpressionId = value; }

        [XmlIgnore]
        public PrimaryExpression Base { get => PrimaryExpression; set => PrimaryExpression = value; }

    }
}
