// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class PivotedTableReferenceAggregateFunctionIdentifierLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("MultiPartIdentifierId")]
        public string MultiPartIdentifierId { get; set; } = string.Empty;

        [XmlAttribute("PivotedTableReferenceId")]
        public string PivotedTableReferenceId { get; set; } = string.Empty;

        [XmlIgnore]
        public MultiPartIdentifier MultiPartIdentifier { get; set; } = null!;

        [XmlIgnore]
        public PivotedTableReference PivotedTableReference { get; set; } = null!;

    }
}
