// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class PivotedTableReferenceInColumnsItem
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("IdentifierId")]
        public string IdentifierId { get; set; } = string.Empty;

        [XmlAttribute("PivotedTableReferenceId")]
        public string PivotedTableReferenceId { get; set; } = string.Empty;

        [XmlElement("Ordinal")]
        public string Ordinal { get; set; } = string.Empty;
        public bool ShouldSerializeOrdinal() => !string.IsNullOrWhiteSpace(Ordinal);

        [XmlIgnore]
        public Identifier Identifier { get; set; } = null!;

        [XmlIgnore]
        public PivotedTableReference PivotedTableReference { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => PivotedTableReferenceId; set => PivotedTableReferenceId = value; }

        [XmlIgnore]
        public PivotedTableReference Owner { get => PivotedTableReference; set => PivotedTableReference = value; }

        [XmlIgnore]
        public string ValueId { get => IdentifierId; set => IdentifierId = value; }

        [XmlIgnore]
        public Identifier Value { get => Identifier; set => Identifier = value; }

    }
}
