// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class QualifiedJoin
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("JoinTableReferenceId")]
        public string JoinTableReferenceId { get; set; } = string.Empty;

        [XmlElement("JoinHint")]
        public string JoinHint { get; set; } = string.Empty;
        public bool ShouldSerializeJoinHint() => !string.IsNullOrWhiteSpace(JoinHint);

        [XmlElement("QualifiedJoinType")]
        public string QualifiedJoinType { get; set; } = string.Empty;
        public bool ShouldSerializeQualifiedJoinType() => !string.IsNullOrWhiteSpace(QualifiedJoinType);

        [XmlIgnore]
        public JoinTableReference JoinTableReference { get; set; } = null!;

    }
}
