// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class QueryExpressionOrderByClauseLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("OrderByClauseId")]
        public string OrderByClauseId { get; set; } = string.Empty;

        [XmlAttribute("QueryExpressionId")]
        public string QueryExpressionId { get; set; } = string.Empty;

        [XmlIgnore]
        public OrderByClause OrderByClause { get; set; } = null!;

        [XmlIgnore]
        public QueryExpression QueryExpression { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => QueryExpressionId; set => QueryExpressionId = value; }

        [XmlIgnore]
        public QueryExpression Owner { get => QueryExpression; set => QueryExpression = value; }

        [XmlIgnore]
        public string ValueId { get => OrderByClauseId; set => OrderByClauseId = value; }

        [XmlIgnore]
        public OrderByClause Value { get => OrderByClause; set => OrderByClause = value; }

    }
}
