// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class QuerySpecificationHavingClauseLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("HavingClauseId")]
        public string HavingClauseId { get; set; } = string.Empty;

        [XmlAttribute("QuerySpecificationId")]
        public string QuerySpecificationId { get; set; } = string.Empty;

        [XmlIgnore]
        public HavingClause HavingClause { get; set; } = null!;

        [XmlIgnore]
        public QuerySpecification QuerySpecification { get; set; } = null!;

    }
}
