// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class QuerySpecificationFromClauseLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("FromClauseId")]
        public string FromClauseId { get; set; } = string.Empty;

        [XmlAttribute("QuerySpecificationId")]
        public string QuerySpecificationId { get; set; } = string.Empty;

        [XmlIgnore]
        public FromClause FromClause { get; set; } = null!;

        [XmlIgnore]
        public QuerySpecification QuerySpecification { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => QuerySpecificationId; set => QuerySpecificationId = value; }

        [XmlIgnore]
        public QuerySpecification Owner { get => QuerySpecification; set => QuerySpecification = value; }

        [XmlIgnore]
        public string ValueId { get => FromClauseId; set => FromClauseId = value; }

        [XmlIgnore]
        public FromClause Value { get => FromClause; set => FromClause = value; }

    }
}
