// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class QuerySpecificationHavingClauseLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("HavingClauseId")]
        public string HavingClauseId { get; set; } = string.Empty;

        [XmlAttribute("QuerySpecificationId")]
        public string QuerySpecificationId { get; set; } = string.Empty;

        [XmlIgnore]
        public HavingClause HavingClause { get; set; } = null!;

        [XmlIgnore]
        public QuerySpecification QuerySpecification { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => QuerySpecificationId; set => QuerySpecificationId = value; }

        [XmlIgnore]
        public QuerySpecification Owner { get => QuerySpecification; set => QuerySpecification = value; }

        [XmlIgnore]
        public string ValueId { get => HavingClauseId; set => HavingClauseId = value; }

        [XmlIgnore]
        public HavingClause Value { get => HavingClause; set => HavingClause = value; }

    }
}
