// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class QuerySpecificationWhereClauseLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("QuerySpecificationId")]
        public string QuerySpecificationId { get; set; } = string.Empty;

        [XmlAttribute("WhereClauseId")]
        public string WhereClauseId { get; set; } = string.Empty;

        [XmlIgnore]
        public QuerySpecification QuerySpecification { get; set; } = null!;

        [XmlIgnore]
        public WhereClause WhereClause { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => QuerySpecificationId; set => QuerySpecificationId = value; }

        [XmlIgnore]
        public QuerySpecification Owner { get => QuerySpecification; set => QuerySpecification = value; }

        [XmlIgnore]
        public string ValueId { get => WhereClauseId; set => WhereClauseId = value; }

        [XmlIgnore]
        public WhereClause Value { get => WhereClause; set => WhereClause = value; }

    }
}
