// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class SchemaObjectFunctionTableReferenceParametersItem
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("ScalarExpressionId")]
        public string ScalarExpressionId { get; set; } = string.Empty;

        [XmlAttribute("SchemaObjectFunctionTableReferenceId")]
        public string SchemaObjectFunctionTableReferenceId { get; set; } = string.Empty;

        [XmlElement("Ordinal")]
        public string Ordinal { get; set; } = string.Empty;
        public bool ShouldSerializeOrdinal() => !string.IsNullOrWhiteSpace(Ordinal);

        [XmlIgnore]
        public ScalarExpression ScalarExpression { get; set; } = null!;

        [XmlIgnore]
        public SchemaObjectFunctionTableReference SchemaObjectFunctionTableReference { get; set; } = null!;

    }
}
