// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class SearchedWhenClauseWhenExpressionLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("BooleanExpressionId")]
        public string BooleanExpressionId { get; set; } = string.Empty;

        [XmlAttribute("SearchedWhenClauseId")]
        public string SearchedWhenClauseId { get; set; } = string.Empty;

        [XmlIgnore]
        public BooleanExpression BooleanExpression { get; set; } = null!;

        [XmlIgnore]
        public SearchedWhenClause SearchedWhenClause { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => SearchedWhenClauseId; set => SearchedWhenClauseId = value; }

        [XmlIgnore]
        public SearchedWhenClause Owner { get => SearchedWhenClause; set => SearchedWhenClause = value; }

        [XmlIgnore]
        public string ValueId { get => BooleanExpressionId; set => BooleanExpressionId = value; }

        [XmlIgnore]
        public BooleanExpression Value { get => BooleanExpression; set => BooleanExpression = value; }

    }
}
