// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class SearchedWhenClause
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("WhenClauseId")]
        public string WhenClauseId { get; set; } = string.Empty;

        [XmlIgnore]
        public WhenClause WhenClause { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string BaseId { get => WhenClauseId; set => WhenClauseId = value; }

        [XmlIgnore]
        public WhenClause Base { get => WhenClause; set => WhenClause = value; }

    }
}
