// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class SearchedCaseExpressionWhenClausesItem
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("SearchedCaseExpressionId")]
        public string SearchedCaseExpressionId { get; set; } = string.Empty;

        [XmlAttribute("SearchedWhenClauseId")]
        public string SearchedWhenClauseId { get; set; } = string.Empty;

        [XmlElement("Ordinal")]
        public string Ordinal { get; set; } = string.Empty;
        public bool ShouldSerializeOrdinal() => !string.IsNullOrWhiteSpace(Ordinal);

        [XmlIgnore]
        public SearchedCaseExpression SearchedCaseExpression { get; set; } = null!;

        [XmlIgnore]
        public SearchedWhenClause SearchedWhenClause { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => SearchedCaseExpressionId; set => SearchedCaseExpressionId = value; }

        [XmlIgnore]
        public SearchedCaseExpression Owner { get => SearchedCaseExpression; set => SearchedCaseExpression = value; }

        [XmlIgnore]
        public string ValueId { get => SearchedWhenClauseId; set => SearchedWhenClauseId = value; }

        [XmlIgnore]
        public SearchedWhenClause Value { get => SearchedWhenClause; set => SearchedWhenClause = value; }

    }
}
