// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class SelectStatementQueryExpressionLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("QueryExpressionId")]
        public string QueryExpressionId { get; set; } = string.Empty;

        [XmlAttribute("SelectStatementId")]
        public string SelectStatementId { get; set; } = string.Empty;

        [XmlIgnore]
        public QueryExpression QueryExpression { get; set; } = null!;

        [XmlIgnore]
        public SelectStatement SelectStatement { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => SelectStatementId; set => SelectStatementId = value; }

        [XmlIgnore]
        public SelectStatement Owner { get => SelectStatement; set => SelectStatement = value; }

        [XmlIgnore]
        public string ValueId { get => QueryExpressionId; set => QueryExpressionId = value; }

        [XmlIgnore]
        public QueryExpression Value { get => QueryExpression; set => QueryExpression = value; }

    }
}
