// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class SelectScalarExpressionColumnNameLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("IdentifierOrValueExpressionId")]
        public string IdentifierOrValueExpressionId { get; set; } = string.Empty;

        [XmlAttribute("SelectScalarExpressionId")]
        public string SelectScalarExpressionId { get; set; } = string.Empty;

        [XmlIgnore]
        public IdentifierOrValueExpression IdentifierOrValueExpression { get; set; } = null!;

        [XmlIgnore]
        public SelectScalarExpression SelectScalarExpression { get; set; } = null!;

    }
}
