// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class SelectStarExpression
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("SelectElementId")]
        public string SelectElementId { get; set; } = string.Empty;

        [XmlIgnore]
        public SelectElement SelectElement { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string BaseId { get => SelectElementId; set => SelectElementId = value; }

        [XmlIgnore]
        public SelectElement Base { get => SelectElement; set => SelectElement = value; }

    }
}
