// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class SelectStarExpressionQualifierLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("MultiPartIdentifierId")]
        public string MultiPartIdentifierId { get; set; } = string.Empty;

        [XmlAttribute("SelectStarExpressionId")]
        public string SelectStarExpressionId { get; set; } = string.Empty;

        [XmlIgnore]
        public MultiPartIdentifier MultiPartIdentifier { get; set; } = null!;

        [XmlIgnore]
        public SelectStarExpression SelectStarExpression { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => SelectStarExpressionId; set => SelectStarExpressionId = value; }

        [XmlIgnore]
        public SelectStarExpression Owner { get => SelectStarExpression; set => SelectStarExpression = value; }

        [XmlIgnore]
        public string ValueId { get => MultiPartIdentifierId; set => MultiPartIdentifierId = value; }

        [XmlIgnore]
        public MultiPartIdentifier Value { get => MultiPartIdentifier; set => MultiPartIdentifier = value; }

    }
}
