// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class SimpleCaseExpression
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("CaseExpressionId")]
        public string CaseExpressionId { get; set; } = string.Empty;

        [XmlIgnore]
        public CaseExpression CaseExpression { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string BaseId { get => CaseExpressionId; set => CaseExpressionId = value; }

        [XmlIgnore]
        public CaseExpression Base { get => CaseExpression; set => CaseExpression = value; }

    }
}
