// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class SqlDataTypeReference
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("ParameterizedDataTypeReferenceId")]
        public string ParameterizedDataTypeReferenceId { get; set; } = string.Empty;

        [XmlElement("SqlDataTypeOption")]
        public string SqlDataTypeOption { get; set; } = string.Empty;
        public bool ShouldSerializeSqlDataTypeOption() => !string.IsNullOrWhiteSpace(SqlDataTypeOption);

        [XmlIgnore]
        public ParameterizedDataTypeReference ParameterizedDataTypeReference { get; set; } = null!;

    }
}
