// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class StatementWithCtesAndXmlNamespacesWithCtesAndXmlNamespacesLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("StatementWithCtesAndXmlNamespacesId")]
        public string StatementWithCtesAndXmlNamespacesId { get; set; } = string.Empty;

        [XmlAttribute("WithCtesAndXmlNamespacesId")]
        public string WithCtesAndXmlNamespacesId { get; set; } = string.Empty;

        [XmlIgnore]
        public StatementWithCtesAndXmlNamespaces StatementWithCtesAndXmlNamespaces { get; set; } = null!;

        [XmlIgnore]
        public WithCtesAndXmlNamespaces WithCtesAndXmlNamespaces { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => StatementWithCtesAndXmlNamespacesId; set => StatementWithCtesAndXmlNamespacesId = value; }

        [XmlIgnore]
        public StatementWithCtesAndXmlNamespaces Owner { get => StatementWithCtesAndXmlNamespaces; set => StatementWithCtesAndXmlNamespaces = value; }

        [XmlIgnore]
        public string ValueId { get => WithCtesAndXmlNamespacesId; set => WithCtesAndXmlNamespacesId = value; }

        [XmlIgnore]
        public WithCtesAndXmlNamespaces Value { get => WithCtesAndXmlNamespaces; set => WithCtesAndXmlNamespaces = value; }

    }
}
