// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class StatementWithCtesAndXmlNamespaces
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("TSqlStatementId")]
        public string TSqlStatementId { get; set; } = string.Empty;

        [XmlIgnore]
        public TSqlStatement TSqlStatement { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string BaseId { get => TSqlStatementId; set => TSqlStatementId = value; }

        [XmlIgnore]
        public TSqlStatement Base { get => TSqlStatement; set => TSqlStatement = value; }

    }
}
