// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class SubqueryComparisonPredicateExpressionLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("ScalarExpressionId")]
        public string ScalarExpressionId { get; set; } = string.Empty;

        [XmlAttribute("SubqueryComparisonPredicateId")]
        public string SubqueryComparisonPredicateId { get; set; } = string.Empty;

        [XmlIgnore]
        public ScalarExpression ScalarExpression { get; set; } = null!;

        [XmlIgnore]
        public SubqueryComparisonPredicate SubqueryComparisonPredicate { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => SubqueryComparisonPredicateId; set => SubqueryComparisonPredicateId = value; }

        [XmlIgnore]
        public SubqueryComparisonPredicate Owner { get => SubqueryComparisonPredicate; set => SubqueryComparisonPredicate = value; }

        [XmlIgnore]
        public string ValueId { get => ScalarExpressionId; set => ScalarExpressionId = value; }

        [XmlIgnore]
        public ScalarExpression Value { get => ScalarExpression; set => ScalarExpression = value; }

    }
}
