// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class TableReferenceWithAlias
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("TableReferenceId")]
        public string TableReferenceId { get; set; } = string.Empty;

        [XmlElement("ForPath")]
        public string ForPath { get; set; } = string.Empty;
        public bool ShouldSerializeForPath() => !string.IsNullOrWhiteSpace(ForPath);

        [XmlIgnore]
        public TableReference TableReference { get; set; } = null!;

    }
}
