// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class TableSampleClause
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlElement("System")]
        public string System { get; set; } = string.Empty;
        public bool ShouldSerializeSystem() => !string.IsNullOrWhiteSpace(System);

        [XmlElement("TableSampleClauseOption")]
        public string TableSampleClauseOption { get; set; } = string.Empty;
        public bool ShouldSerializeTableSampleClauseOption() => !string.IsNullOrWhiteSpace(TableSampleClauseOption);

    }
}
