// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class TransformScript
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlElement("LanguageProfileId")]
        public string LanguageProfileId { get; set; } = string.Empty;
        public bool ShouldSerializeLanguageProfileId() => !string.IsNullOrWhiteSpace(LanguageProfileId);

        [XmlElement("Name")]
        public string Name { get; set; } = string.Empty;

        [XmlElement("ScriptObjectKind")]
        public string ScriptObjectKind { get; set; } = string.Empty;
        public bool ShouldSerializeScriptObjectKind() => !string.IsNullOrWhiteSpace(ScriptObjectKind);

        [XmlElement("SourcePath")]
        public string SourcePath { get; set; } = string.Empty;
        public bool ShouldSerializeSourcePath() => !string.IsNullOrWhiteSpace(SourcePath);

        [XmlElement("TargetSqlIdentifier")]
        public string TargetSqlIdentifier { get; set; } = string.Empty;

    }
}
