// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class UnpivotedTableReferenceValueColumnLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("IdentifierId")]
        public string IdentifierId { get; set; } = string.Empty;

        [XmlAttribute("UnpivotedTableReferenceId")]
        public string UnpivotedTableReferenceId { get; set; } = string.Empty;

        [XmlIgnore]
        public Identifier Identifier { get; set; } = null!;

        [XmlIgnore]
        public UnpivotedTableReference UnpivotedTableReference { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => UnpivotedTableReferenceId; set => UnpivotedTableReferenceId = value; }

        [XmlIgnore]
        public UnpivotedTableReference Owner { get => UnpivotedTableReference; set => UnpivotedTableReference = value; }

        [XmlIgnore]
        public string ValueId { get => IdentifierId; set => IdentifierId = value; }

        [XmlIgnore]
        public Identifier Value { get => Identifier; set => Identifier = value; }

    }
}
