// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class UnqualifiedJoin
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("JoinTableReferenceId")]
        public string JoinTableReferenceId { get; set; } = string.Empty;

        [XmlElement("UnqualifiedJoinType")]
        public string UnqualifiedJoinType { get; set; } = string.Empty;
        public bool ShouldSerializeUnqualifiedJoinType() => !string.IsNullOrWhiteSpace(UnqualifiedJoinType);

        [XmlIgnore]
        public JoinTableReference JoinTableReference { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string BaseId { get => JoinTableReferenceId; set => JoinTableReferenceId = value; }

        [XmlIgnore]
        public JoinTableReference Base { get => JoinTableReference; set => JoinTableReference = value; }

    }
}
