// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class WindowFrameClauseTopLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("WindowDelimiterId")]
        public string WindowDelimiterId { get; set; } = string.Empty;

        [XmlAttribute("WindowFrameClauseId")]
        public string WindowFrameClauseId { get; set; } = string.Empty;

        [XmlIgnore]
        public WindowDelimiter WindowDelimiter { get; set; } = null!;

        [XmlIgnore]
        public WindowFrameClause WindowFrameClause { get; set; } = null!;

    }
}
