// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class WithCtesAndXmlNamespacesXmlNamespacesLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("WithCtesAndXmlNamespacesId")]
        public string WithCtesAndXmlNamespacesId { get; set; } = string.Empty;

        [XmlAttribute("XmlNamespacesId")]
        public string XmlNamespacesId { get; set; } = string.Empty;

        [XmlIgnore]
        public WithCtesAndXmlNamespaces WithCtesAndXmlNamespaces { get; set; } = null!;

        [XmlIgnore]
        public XmlNamespaces XmlNamespaces { get; set; } = null!;

    }
}
