// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class WithCtesAndXmlNamespacesCommonTableExpressionsItem
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("CommonTableExpressionId")]
        public string CommonTableExpressionId { get; set; } = string.Empty;

        [XmlAttribute("WithCtesAndXmlNamespacesId")]
        public string WithCtesAndXmlNamespacesId { get; set; } = string.Empty;

        [XmlElement("Ordinal")]
        public string Ordinal { get; set; } = string.Empty;
        public bool ShouldSerializeOrdinal() => !string.IsNullOrWhiteSpace(Ordinal);

        [XmlIgnore]
        public CommonTableExpression CommonTableExpression { get; set; } = null!;

        [XmlIgnore]
        public WithCtesAndXmlNamespaces WithCtesAndXmlNamespaces { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => WithCtesAndXmlNamespacesId; set => WithCtesAndXmlNamespacesId = value; }

        [XmlIgnore]
        public WithCtesAndXmlNamespaces Owner { get => WithCtesAndXmlNamespaces; set => WithCtesAndXmlNamespaces = value; }

        [XmlIgnore]
        public string ValueId { get => CommonTableExpressionId; set => CommonTableExpressionId = value; }

        [XmlIgnore]
        public CommonTableExpression Value { get => CommonTableExpression; set => CommonTableExpression = value; }

    }
}
