// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class XmlNamespacesElementStringLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("StringLiteralId")]
        public string StringLiteralId { get; set; } = string.Empty;

        [XmlAttribute("XmlNamespacesElementId")]
        public string XmlNamespacesElementId { get; set; } = string.Empty;

        [XmlIgnore]
        public StringLiteral StringLiteral { get; set; } = null!;

        [XmlIgnore]
        public XmlNamespacesElement XmlNamespacesElement { get; set; } = null!;

        // Compatibility aliases for legacy Owner/Value/Base naming.
        [XmlIgnore]
        public string OwnerId { get => XmlNamespacesElementId; set => XmlNamespacesElementId = value; }

        [XmlIgnore]
        public XmlNamespacesElement Owner { get => XmlNamespacesElement; set => XmlNamespacesElement = value; }

        [XmlIgnore]
        public string ValueId { get => StringLiteralId; set => StringLiteralId = value; }

        [XmlIgnore]
        public StringLiteral Value { get => StringLiteral; set => StringLiteral = value; }

    }
}
