// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Xml.Serialization;

namespace MetaTransformScript
{
    public sealed class XmlNodesTableReferenceXQueryStringLink
    {
        [XmlAttribute("Id")]
        public string Id { get; set; } = string.Empty;

        [XmlAttribute("StringLiteralId")]
        public string StringLiteralId { get; set; } = string.Empty;

        [XmlAttribute("XmlNodesTableReferenceId")]
        public string XmlNodesTableReferenceId { get; set; } = string.Empty;

        [XmlIgnore]
        public StringLiteral StringLiteral { get; set; } = null!;

        [XmlIgnore]
        public XmlNodesTableReference XmlNodesTableReference { get; set; } = null!;

    }
}
