// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaTransformScript
// Regenerate with:
//   meta generate csharp --workspace ".\MetaTransformScript" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaTransformScript
{
    public sealed class XmlNodesTableReferenceXQueryStringLink
    {
        public string Id { get; set; } = string.Empty;

        public StringLiteral StringLiteral { get; set; } = null!;

        public XmlNodesTableReference XmlNodesTableReference { get; set; } = null!;

    }
}
