<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>meta-multi-dimensional</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meta.Core" Version="$(MetaFoundationPackageVersion)" />
    <PackageReference Include="MetaCli.Core" Version="$(MetaFoundationPackageVersion)" />
    <ProjectReference Include="..\Core\MetaMultiDimensional.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="meta-multi-dimensional.MetaCli\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
