// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaRawDataVault
// Regenerate with:
//   meta generate csharp --workspace ".\MetaRawDataVault" --out <dir> --tooling
// </auto-generated>

#nullable enable

using Meta.Core.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace MetaRawDataVault
{
    public static class MetaRawDataVaultTooling
    {
        public static MetaRawDataVaultModel Load(
            string workspacePath,
            bool searchUpward = false)
        {
            return MetaRawDataVaultModel.LoadFromXmlWorkspace(workspacePath, searchUpward);
        }

        public static Task<MetaRawDataVaultModel> LoadAsync(
            string workspacePath,
            bool searchUpward = false,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return MetaRawDataVaultModel.LoadFromXmlWorkspaceAsync(workspacePath, searchUpward, cancellationToken);
        }

        public static string CreateWorkspace(string workspacePath)
        {
            return TypedWorkspaceXmlSerializer.CreateWorkspace<MetaRawDataVaultModel>(workspacePath);
        }

        public static bool IsWorkspace(string workspacePath)
        {
            return TypedWorkspaceXmlSerializer.IsWorkspace<MetaRawDataVaultModel>(workspacePath);
        }

        public static void Save(MetaRawDataVaultModel model, string workspacePath)
        {
            if (model == null)
            {
                throw new global::System.ArgumentNullException(nameof(model));
            }

            model.SaveToXmlWorkspace(workspacePath);
        }

        public static Task SaveAsync(MetaRawDataVaultModel model, string workspacePath,
            CancellationToken cancellationToken = default)
        {
            if (model == null)
            {
                throw new global::System.ArgumentNullException(nameof(model));
            }

            cancellationToken.ThrowIfCancellationRequested();
            model.SaveToXmlWorkspace(workspacePath);
            return Task.CompletedTask;
        }
    }
}
