// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaRawDataVault
// Regenerate with:
//   meta generate csharp --workspace ".\MetaRawDataVault" --out <dir> --tooling
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using Meta.Core.Serialization;

namespace MetaRawDataVault
{
    public sealed partial class MetaRawDataVaultModel : IMetaWorkspaceModel<MetaRawDataVaultModel>
    {
        public static MetaRawDataVaultModel CreateEmpty() => new();

        public List<Field> FieldList { get; set; } = new();

        public List<FieldDataTypeDetail> FieldDataTypeDetailList { get; set; } = new();

        public List<RawHub> RawHubList { get; set; } = new();

        public List<RawHubKeyPart> RawHubKeyPartList { get; set; } = new();

        public List<RawHubSatellite> RawHubSatelliteList { get; set; } = new();

        public List<RawHubSatelliteAttribute> RawHubSatelliteAttributeList { get; set; } = new();

        public List<RawLink> RawLinkList { get; set; } = new();

        public List<RawLinkHub> RawLinkHubList { get; set; } = new();

        public List<RawLinkSatellite> RawLinkSatelliteList { get; set; } = new();

        public List<RawLinkSatelliteAttribute> RawLinkSatelliteAttributeList { get; set; } = new();

        public static MetaRawDataVaultModel LoadFromXmlWorkspace(
            string workspacePath,
            bool searchUpward = false)
        {
            return MetaRawDataVaultModelXmlSerializer.Load(workspacePath, searchUpward);
        }

        public static Task<MetaRawDataVaultModel> LoadFromXmlWorkspaceAsync(
            string workspacePath,
            bool searchUpward = false,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return Task.FromResult(LoadFromXmlWorkspace(workspacePath, searchUpward));
        }

        public void SaveToXmlWorkspace(string workspacePath)
        {
            MetaRawDataVaultModelXmlSerializer.Save(this, workspacePath);
        }

        public Task SaveToXmlWorkspaceAsync(
            string workspacePath,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            SaveToXmlWorkspace(workspacePath);
            return Task.CompletedTask;
        }
    }

    internal static class MetaRawDataVaultModelXmlSerializer
    {
        private static readonly UTF8Encoding Utf8NoBom = new(encoderShouldEmitUTF8Identifier: false);

        internal static MetaRawDataVaultModel Load(string workspacePath, bool searchUpward)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(workspacePath);
            if (searchUpward)
            {
                throw new NotSupportedException("Typed workspace loading does not search parent directories. Pass an explicit workspace path.");
            }

            if (HasRuntimeExtendedShape())
            {
                return TypedWorkspaceXmlSerializer.Load<MetaRawDataVaultModel>(workspacePath, searchUpward);
            }

            var workspaceRootPath = TypedWorkspaceXmlSerializer.RequireWorkspace<MetaRawDataVaultModel>(workspacePath);

            var model = new MetaRawDataVaultModel();
            var loadState = new LoadState();
            var relationshipBuffers = new RelationshipBuffers();
            var instanceDirectoryPath = TypedWorkspaceXmlSerializer.ResolveInstanceDirectoryPath(workspaceRootPath);
            if (!Directory.Exists(instanceDirectoryPath))
            {
                return model;
            }

            foreach (var shardPath in Directory.GetFiles(instanceDirectoryPath, "*.xml")
                         .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
                         .ThenBy(path => path, StringComparer.Ordinal))
            {
                LoadShard(model, shardPath, loadState, relationshipBuffers);
            }

            var loadIndexes = new LoadIndexes(model);
            ResolveRelationshipGroup1(loadIndexes, relationshipBuffers);
            return model;
        }

        internal static void Save(MetaRawDataVaultModel model, string workspacePath)
        {
            ArgumentNullException.ThrowIfNull(model);
            ArgumentException.ThrowIfNullOrWhiteSpace(workspacePath);
            if (HasRuntimeExtendedShape())
            {
                TypedWorkspaceXmlSerializer.Save(model, workspacePath);
                return;
            }

            TypedWorkspaceXmlSerializer.SaveModel(model, workspacePath);

            var saveIndexes = new SaveIndexes(model);

            var workspaceRootPath = Path.GetFullPath(workspacePath);
            var instanceDirectoryPath = TypedWorkspaceXmlSerializer.ResolveInstanceDirectoryPath(workspaceRootPath);
            Directory.CreateDirectory(instanceDirectoryPath);
            var expectedShardPaths = BuildExpectedShardPaths(instanceDirectoryPath);
            SaveShardGroup1(model, instanceDirectoryPath, saveIndexes);
            foreach (var shardPath in Directory.GetFiles(instanceDirectoryPath, "*.xml")
                         .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
                         .ThenBy(path => path, StringComparer.Ordinal))
            {
                if (!expectedShardPaths.Contains(Path.GetFullPath(shardPath)))
                {
                    File.Delete(shardPath);
                }
            }
        }

        private static void SaveShardGroup1(MetaRawDataVaultModel model, string instanceDirectoryPath, SaveIndexes saveIndexes)
        {
            model.FieldList ??= new List<Field>();
            var fieldShardPath = Path.Combine(instanceDirectoryPath, "Field.xml");
            if (model.FieldList.Count == 0)
            {
                DeleteIfExists(fieldShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(fieldShardPath, SerializeFieldShard(model, saveIndexes));
            }

            model.FieldDataTypeDetailList ??= new List<FieldDataTypeDetail>();
            var fieldDataTypeDetailShardPath = Path.Combine(instanceDirectoryPath, "FieldDataTypeDetail.xml");
            if (model.FieldDataTypeDetailList.Count == 0)
            {
                DeleteIfExists(fieldDataTypeDetailShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(fieldDataTypeDetailShardPath, SerializeFieldDataTypeDetailShard(model, saveIndexes));
            }

            model.RawHubList ??= new List<RawHub>();
            var rawHubShardPath = Path.Combine(instanceDirectoryPath, "RawHub.xml");
            if (model.RawHubList.Count == 0)
            {
                DeleteIfExists(rawHubShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(rawHubShardPath, SerializeRawHubShard(model, saveIndexes));
            }

            model.RawHubKeyPartList ??= new List<RawHubKeyPart>();
            var rawHubKeyPartShardPath = Path.Combine(instanceDirectoryPath, "RawHubKeyPart.xml");
            if (model.RawHubKeyPartList.Count == 0)
            {
                DeleteIfExists(rawHubKeyPartShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(rawHubKeyPartShardPath, SerializeRawHubKeyPartShard(model, saveIndexes));
            }

            model.RawHubSatelliteList ??= new List<RawHubSatellite>();
            var rawHubSatelliteShardPath = Path.Combine(instanceDirectoryPath, "RawHubSatellite.xml");
            if (model.RawHubSatelliteList.Count == 0)
            {
                DeleteIfExists(rawHubSatelliteShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(rawHubSatelliteShardPath, SerializeRawHubSatelliteShard(model, saveIndexes));
            }

            model.RawHubSatelliteAttributeList ??= new List<RawHubSatelliteAttribute>();
            var rawHubSatelliteAttributeShardPath = Path.Combine(instanceDirectoryPath, "RawHubSatelliteAttribute.xml");
            if (model.RawHubSatelliteAttributeList.Count == 0)
            {
                DeleteIfExists(rawHubSatelliteAttributeShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(rawHubSatelliteAttributeShardPath, SerializeRawHubSatelliteAttributeShard(model, saveIndexes));
            }

            model.RawLinkList ??= new List<RawLink>();
            var rawLinkShardPath = Path.Combine(instanceDirectoryPath, "RawLink.xml");
            if (model.RawLinkList.Count == 0)
            {
                DeleteIfExists(rawLinkShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(rawLinkShardPath, SerializeRawLinkShard(model, saveIndexes));
            }

            model.RawLinkHubList ??= new List<RawLinkHub>();
            var rawLinkHubShardPath = Path.Combine(instanceDirectoryPath, "RawLinkHub.xml");
            if (model.RawLinkHubList.Count == 0)
            {
                DeleteIfExists(rawLinkHubShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(rawLinkHubShardPath, SerializeRawLinkHubShard(model, saveIndexes));
            }

            model.RawLinkSatelliteList ??= new List<RawLinkSatellite>();
            var rawLinkSatelliteShardPath = Path.Combine(instanceDirectoryPath, "RawLinkSatellite.xml");
            if (model.RawLinkSatelliteList.Count == 0)
            {
                DeleteIfExists(rawLinkSatelliteShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(rawLinkSatelliteShardPath, SerializeRawLinkSatelliteShard(model, saveIndexes));
            }

            model.RawLinkSatelliteAttributeList ??= new List<RawLinkSatelliteAttribute>();
            var rawLinkSatelliteAttributeShardPath = Path.Combine(instanceDirectoryPath, "RawLinkSatelliteAttribute.xml");
            if (model.RawLinkSatelliteAttributeList.Count == 0)
            {
                DeleteIfExists(rawLinkSatelliteAttributeShardPath);
            }
            else
            {
                TypedWorkspaceXmlSerializer.WriteBytesIfChanged(rawLinkSatelliteAttributeShardPath, SerializeRawLinkSatelliteAttributeShard(model, saveIndexes));
            }

        }

        private static void LoadShard(MetaRawDataVaultModel model, string shardPath, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            using var reader = XmlReader.Create(shardPath, new XmlReaderSettings
            {
                IgnoreComments = true,
                IgnoreWhitespace = true,
            });
            reader.MoveToContent();
            if (reader.NodeType != XmlNodeType.Element || !string.Equals(reader.LocalName, "MetaRawDataVault", StringComparison.Ordinal))
            {
                throw new InvalidDataException($"Instance XML '{shardPath}' root must be <MetaRawDataVault>.");
            }
            if (reader.IsEmptyElement)
            {
                reader.Read();
                return;
            }
            reader.ReadStartElement("MetaRawDataVault");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "FieldList":
                        LoadFieldList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "FieldDataTypeDetailList":
                        LoadFieldDataTypeDetailList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "RawHubList":
                        LoadRawHubList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "RawHubKeyPartList":
                        LoadRawHubKeyPartList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "RawHubSatelliteList":
                        LoadRawHubSatelliteList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "RawHubSatelliteAttributeList":
                        LoadRawHubSatelliteAttributeList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "RawLinkList":
                        LoadRawLinkList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "RawLinkHubList":
                        LoadRawLinkHubList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "RawLinkSatelliteList":
                        LoadRawLinkSatelliteList(model, reader, loadState, relationshipBuffers);
                        break;
                    case "RawLinkSatelliteAttributeList":
                        LoadRawLinkSatelliteAttributeList(model, reader, loadState, relationshipBuffers);
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in '{shardPath}'.");
                }
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static void LoadFieldList(MetaRawDataVaultModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("FieldList");
                return;
            }

            reader.ReadStartElement("FieldList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "Field", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'FieldList'.");
                }
                var row = ReadField(reader, relationshipBuffers);
                loadState.AddFieldId(row.Id);
                model.FieldList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static Field ReadField(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new Field();
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'Field'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("Field");
                return row;
            }

            reader.ReadStartElement("Field");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "DataTypeId":
                        row.DataTypeId = reader.ReadElementContentAsString();
                        break;
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'Field'.");
                }
            }
            reader.ReadEndElement();
            return row;
        }

        private static byte[] SerializeFieldShard(MetaRawDataVaultModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaRawDataVault>\n");
            builder.Append("  <FieldList>\n");
            foreach (var row in model.FieldList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'Field' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'Field' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <Field Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "DataTypeId", RequireText(row.DataTypeId, $"Entity 'Field' row '{row.Id}' is missing required property 'DataTypeId'."), "      ");
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'Field' row '{row.Id}' is missing required property 'Name'."), "      ");
                builder.Append("    </Field>\n");
            }
            builder.Append("  </FieldList>\n");
            builder.Append("</MetaRawDataVault>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadFieldDataTypeDetailList(MetaRawDataVaultModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("FieldDataTypeDetailList");
                return;
            }

            reader.ReadStartElement("FieldDataTypeDetailList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "FieldDataTypeDetail", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'FieldDataTypeDetailList'.");
                }
                var row = ReadFieldDataTypeDetail(reader, relationshipBuffers);
                loadState.AddFieldDataTypeDetailId(row.Id);
                model.FieldDataTypeDetailList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static FieldDataTypeDetail ReadFieldDataTypeDetail(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new FieldDataTypeDetail();
            var relationships = new FieldDataTypeDetailRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "FieldId":
                            relationships.FieldId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'FieldDataTypeDetail'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("FieldDataTypeDetail");
                (relationshipBuffers.FieldDataTypeDetailRelationships ??= new List<FieldDataTypeDetailRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("FieldDataTypeDetail");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    case "Value":
                        row.Value = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'FieldDataTypeDetail'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.FieldDataTypeDetailRelationships ??= new List<FieldDataTypeDetailRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeFieldDataTypeDetailShard(MetaRawDataVaultModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaRawDataVault>\n");
            builder.Append("  <FieldDataTypeDetailList>\n");
            foreach (var row in model.FieldDataTypeDetailList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'FieldDataTypeDetail' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'FieldDataTypeDetail' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <FieldDataTypeDetail Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var fieldId = RequireIdentity(row.Field?.Id, $"Relationship 'FieldDataTypeDetail.FieldId' on row 'FieldDataTypeDetail:{row.Id}' is empty.");
                if (!saveIndexes.FieldListById.TryGetValue(fieldId, out var fieldCanonical) || !ReferenceEquals(fieldCanonical, row.Field))
                {
                    throw new InvalidOperationException($"Relationship 'FieldDataTypeDetail.FieldId' on row 'FieldDataTypeDetail:{row.Id}' references an object that is not the canonical row for Id '{fieldId}'.");
                }
                builder.Append(' ');
                builder.Append("FieldId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, fieldId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'FieldDataTypeDetail' row '{row.Id}' is missing required property 'Name'."), "      ");
                AppendElement(builder, "Value", RequireText(row.Value, $"Entity 'FieldDataTypeDetail' row '{row.Id}' is missing required property 'Value'."), "      ");
                builder.Append("    </FieldDataTypeDetail>\n");
            }
            builder.Append("  </FieldDataTypeDetailList>\n");
            builder.Append("</MetaRawDataVault>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadRawHubList(MetaRawDataVaultModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawHubList");
                return;
            }

            reader.ReadStartElement("RawHubList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "RawHub", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'RawHubList'.");
                }
                var row = ReadRawHub(reader, relationshipBuffers);
                loadState.AddRawHubId(row.Id);
                model.RawHubList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static RawHub ReadRawHub(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new RawHub();
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'RawHub'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawHub");
                return row;
            }

            reader.ReadStartElement("RawHub");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'RawHub'.");
                }
            }
            reader.ReadEndElement();
            return row;
        }

        private static byte[] SerializeRawHubShard(MetaRawDataVaultModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaRawDataVault>\n");
            builder.Append("  <RawHubList>\n");
            foreach (var row in model.RawHubList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'RawHub' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'RawHub' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <RawHub Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'RawHub' row '{row.Id}' is missing required property 'Name'."), "      ");
                builder.Append("    </RawHub>\n");
            }
            builder.Append("  </RawHubList>\n");
            builder.Append("</MetaRawDataVault>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadRawHubKeyPartList(MetaRawDataVaultModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawHubKeyPartList");
                return;
            }

            reader.ReadStartElement("RawHubKeyPartList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "RawHubKeyPart", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'RawHubKeyPartList'.");
                }
                var row = ReadRawHubKeyPart(reader, relationshipBuffers);
                loadState.AddRawHubKeyPartId(row.Id);
                model.RawHubKeyPartList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static RawHubKeyPart ReadRawHubKeyPart(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new RawHubKeyPart();
            var relationships = new RawHubKeyPartRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "FieldId":
                            relationships.FieldId = reader.Value;
                            break;
                        case "RawHubId":
                            relationships.RawHubId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'RawHubKeyPart'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawHubKeyPart");
                (relationshipBuffers.RawHubKeyPartRelationships ??= new List<RawHubKeyPartRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("RawHubKeyPart");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    case "Ordinal":
                        row.Ordinal = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'RawHubKeyPart'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.RawHubKeyPartRelationships ??= new List<RawHubKeyPartRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeRawHubKeyPartShard(MetaRawDataVaultModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaRawDataVault>\n");
            builder.Append("  <RawHubKeyPartList>\n");
            foreach (var row in model.RawHubKeyPartList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'RawHubKeyPart' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'RawHubKeyPart' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <RawHubKeyPart Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var fieldId = RequireIdentity(row.Field?.Id, $"Relationship 'RawHubKeyPart.FieldId' on row 'RawHubKeyPart:{row.Id}' is empty.");
                if (!saveIndexes.FieldListById.TryGetValue(fieldId, out var fieldCanonical) || !ReferenceEquals(fieldCanonical, row.Field))
                {
                    throw new InvalidOperationException($"Relationship 'RawHubKeyPart.FieldId' on row 'RawHubKeyPart:{row.Id}' references an object that is not the canonical row for Id '{fieldId}'.");
                }
                builder.Append(' ');
                builder.Append("FieldId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, fieldId);
                builder.Append('"');
                var rawHubId = RequireIdentity(row.RawHub?.Id, $"Relationship 'RawHubKeyPart.RawHubId' on row 'RawHubKeyPart:{row.Id}' is empty.");
                if (!saveIndexes.RawHubListById.TryGetValue(rawHubId, out var rawHubCanonical) || !ReferenceEquals(rawHubCanonical, row.RawHub))
                {
                    throw new InvalidOperationException($"Relationship 'RawHubKeyPart.RawHubId' on row 'RawHubKeyPart:{row.Id}' references an object that is not the canonical row for Id '{rawHubId}'.");
                }
                builder.Append(' ');
                builder.Append("RawHubId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, rawHubId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'RawHubKeyPart' row '{row.Id}' is missing required property 'Name'."), "      ");
                AppendElement(builder, "Ordinal", RequireText(row.Ordinal, $"Entity 'RawHubKeyPart' row '{row.Id}' is missing required property 'Ordinal'."), "      ");
                builder.Append("    </RawHubKeyPart>\n");
            }
            builder.Append("  </RawHubKeyPartList>\n");
            builder.Append("</MetaRawDataVault>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadRawHubSatelliteList(MetaRawDataVaultModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawHubSatelliteList");
                return;
            }

            reader.ReadStartElement("RawHubSatelliteList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "RawHubSatellite", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'RawHubSatelliteList'.");
                }
                var row = ReadRawHubSatellite(reader, relationshipBuffers);
                loadState.AddRawHubSatelliteId(row.Id);
                model.RawHubSatelliteList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static RawHubSatellite ReadRawHubSatellite(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new RawHubSatellite();
            var relationships = new RawHubSatelliteRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "RawHubId":
                            relationships.RawHubId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'RawHubSatellite'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawHubSatellite");
                (relationshipBuffers.RawHubSatelliteRelationships ??= new List<RawHubSatelliteRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("RawHubSatellite");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    case "SatelliteKind":
                        row.SatelliteKind = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'RawHubSatellite'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.RawHubSatelliteRelationships ??= new List<RawHubSatelliteRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeRawHubSatelliteShard(MetaRawDataVaultModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaRawDataVault>\n");
            builder.Append("  <RawHubSatelliteList>\n");
            foreach (var row in model.RawHubSatelliteList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'RawHubSatellite' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'RawHubSatellite' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <RawHubSatellite Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var rawHubId = RequireIdentity(row.RawHub?.Id, $"Relationship 'RawHubSatellite.RawHubId' on row 'RawHubSatellite:{row.Id}' is empty.");
                if (!saveIndexes.RawHubListById.TryGetValue(rawHubId, out var rawHubCanonical) || !ReferenceEquals(rawHubCanonical, row.RawHub))
                {
                    throw new InvalidOperationException($"Relationship 'RawHubSatellite.RawHubId' on row 'RawHubSatellite:{row.Id}' references an object that is not the canonical row for Id '{rawHubId}'.");
                }
                builder.Append(' ');
                builder.Append("RawHubId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, rawHubId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'RawHubSatellite' row '{row.Id}' is missing required property 'Name'."), "      ");
                AppendElement(builder, "SatelliteKind", RequireText(row.SatelliteKind, $"Entity 'RawHubSatellite' row '{row.Id}' is missing required property 'SatelliteKind'."), "      ");
                builder.Append("    </RawHubSatellite>\n");
            }
            builder.Append("  </RawHubSatelliteList>\n");
            builder.Append("</MetaRawDataVault>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadRawHubSatelliteAttributeList(MetaRawDataVaultModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawHubSatelliteAttributeList");
                return;
            }

            reader.ReadStartElement("RawHubSatelliteAttributeList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "RawHubSatelliteAttribute", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'RawHubSatelliteAttributeList'.");
                }
                var row = ReadRawHubSatelliteAttribute(reader, relationshipBuffers);
                loadState.AddRawHubSatelliteAttributeId(row.Id);
                model.RawHubSatelliteAttributeList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static RawHubSatelliteAttribute ReadRawHubSatelliteAttribute(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new RawHubSatelliteAttribute();
            var relationships = new RawHubSatelliteAttributeRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "FieldId":
                            relationships.FieldId = reader.Value;
                            break;
                        case "RawHubSatelliteId":
                            relationships.RawHubSatelliteId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'RawHubSatelliteAttribute'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawHubSatelliteAttribute");
                (relationshipBuffers.RawHubSatelliteAttributeRelationships ??= new List<RawHubSatelliteAttributeRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("RawHubSatelliteAttribute");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    case "Ordinal":
                        row.Ordinal = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'RawHubSatelliteAttribute'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.RawHubSatelliteAttributeRelationships ??= new List<RawHubSatelliteAttributeRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeRawHubSatelliteAttributeShard(MetaRawDataVaultModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaRawDataVault>\n");
            builder.Append("  <RawHubSatelliteAttributeList>\n");
            foreach (var row in model.RawHubSatelliteAttributeList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'RawHubSatelliteAttribute' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'RawHubSatelliteAttribute' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <RawHubSatelliteAttribute Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var fieldId = RequireIdentity(row.Field?.Id, $"Relationship 'RawHubSatelliteAttribute.FieldId' on row 'RawHubSatelliteAttribute:{row.Id}' is empty.");
                if (!saveIndexes.FieldListById.TryGetValue(fieldId, out var fieldCanonical) || !ReferenceEquals(fieldCanonical, row.Field))
                {
                    throw new InvalidOperationException($"Relationship 'RawHubSatelliteAttribute.FieldId' on row 'RawHubSatelliteAttribute:{row.Id}' references an object that is not the canonical row for Id '{fieldId}'.");
                }
                builder.Append(' ');
                builder.Append("FieldId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, fieldId);
                builder.Append('"');
                var rawHubSatelliteId = RequireIdentity(row.RawHubSatellite?.Id, $"Relationship 'RawHubSatelliteAttribute.RawHubSatelliteId' on row 'RawHubSatelliteAttribute:{row.Id}' is empty.");
                if (!saveIndexes.RawHubSatelliteListById.TryGetValue(rawHubSatelliteId, out var rawHubSatelliteCanonical) || !ReferenceEquals(rawHubSatelliteCanonical, row.RawHubSatellite))
                {
                    throw new InvalidOperationException($"Relationship 'RawHubSatelliteAttribute.RawHubSatelliteId' on row 'RawHubSatelliteAttribute:{row.Id}' references an object that is not the canonical row for Id '{rawHubSatelliteId}'.");
                }
                builder.Append(' ');
                builder.Append("RawHubSatelliteId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, rawHubSatelliteId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'RawHubSatelliteAttribute' row '{row.Id}' is missing required property 'Name'."), "      ");
                AppendElement(builder, "Ordinal", RequireText(row.Ordinal, $"Entity 'RawHubSatelliteAttribute' row '{row.Id}' is missing required property 'Ordinal'."), "      ");
                builder.Append("    </RawHubSatelliteAttribute>\n");
            }
            builder.Append("  </RawHubSatelliteAttributeList>\n");
            builder.Append("</MetaRawDataVault>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadRawLinkList(MetaRawDataVaultModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawLinkList");
                return;
            }

            reader.ReadStartElement("RawLinkList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "RawLink", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'RawLinkList'.");
                }
                var row = ReadRawLink(reader, relationshipBuffers);
                loadState.AddRawLinkId(row.Id);
                model.RawLinkList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static RawLink ReadRawLink(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new RawLink();
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'RawLink'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawLink");
                return row;
            }

            reader.ReadStartElement("RawLink");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "LinkKind":
                        row.LinkKind = reader.ReadElementContentAsString();
                        break;
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'RawLink'.");
                }
            }
            reader.ReadEndElement();
            return row;
        }

        private static byte[] SerializeRawLinkShard(MetaRawDataVaultModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaRawDataVault>\n");
            builder.Append("  <RawLinkList>\n");
            foreach (var row in model.RawLinkList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'RawLink' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'RawLink' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <RawLink Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "LinkKind", RequireText(row.LinkKind, $"Entity 'RawLink' row '{row.Id}' is missing required property 'LinkKind'."), "      ");
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'RawLink' row '{row.Id}' is missing required property 'Name'."), "      ");
                builder.Append("    </RawLink>\n");
            }
            builder.Append("  </RawLinkList>\n");
            builder.Append("</MetaRawDataVault>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadRawLinkHubList(MetaRawDataVaultModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawLinkHubList");
                return;
            }

            reader.ReadStartElement("RawLinkHubList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "RawLinkHub", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'RawLinkHubList'.");
                }
                var row = ReadRawLinkHub(reader, relationshipBuffers);
                loadState.AddRawLinkHubId(row.Id);
                model.RawLinkHubList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static RawLinkHub ReadRawLinkHub(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new RawLinkHub();
            var relationships = new RawLinkHubRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "RawHubId":
                            relationships.RawHubId = reader.Value;
                            break;
                        case "RawLinkId":
                            relationships.RawLinkId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'RawLinkHub'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawLinkHub");
                (relationshipBuffers.RawLinkHubRelationships ??= new List<RawLinkHubRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("RawLinkHub");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Ordinal":
                        row.Ordinal = reader.ReadElementContentAsString();
                        break;
                    case "RoleName":
                        row.RoleName = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'RawLinkHub'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.RawLinkHubRelationships ??= new List<RawLinkHubRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeRawLinkHubShard(MetaRawDataVaultModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaRawDataVault>\n");
            builder.Append("  <RawLinkHubList>\n");
            foreach (var row in model.RawLinkHubList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'RawLinkHub' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'RawLinkHub' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <RawLinkHub Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var rawHubId = RequireIdentity(row.RawHub?.Id, $"Relationship 'RawLinkHub.RawHubId' on row 'RawLinkHub:{row.Id}' is empty.");
                if (!saveIndexes.RawHubListById.TryGetValue(rawHubId, out var rawHubCanonical) || !ReferenceEquals(rawHubCanonical, row.RawHub))
                {
                    throw new InvalidOperationException($"Relationship 'RawLinkHub.RawHubId' on row 'RawLinkHub:{row.Id}' references an object that is not the canonical row for Id '{rawHubId}'.");
                }
                builder.Append(' ');
                builder.Append("RawHubId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, rawHubId);
                builder.Append('"');
                var rawLinkId = RequireIdentity(row.RawLink?.Id, $"Relationship 'RawLinkHub.RawLinkId' on row 'RawLinkHub:{row.Id}' is empty.");
                if (!saveIndexes.RawLinkListById.TryGetValue(rawLinkId, out var rawLinkCanonical) || !ReferenceEquals(rawLinkCanonical, row.RawLink))
                {
                    throw new InvalidOperationException($"Relationship 'RawLinkHub.RawLinkId' on row 'RawLinkHub:{row.Id}' references an object that is not the canonical row for Id '{rawLinkId}'.");
                }
                builder.Append(' ');
                builder.Append("RawLinkId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, rawLinkId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "Ordinal", RequireText(row.Ordinal, $"Entity 'RawLinkHub' row '{row.Id}' is missing required property 'Ordinal'."), "      ");
                if (!string.IsNullOrWhiteSpace(row.RoleName))
                {
                    AppendElement(builder, "RoleName", row.RoleName!, "      ");
                }
                builder.Append("    </RawLinkHub>\n");
            }
            builder.Append("  </RawLinkHubList>\n");
            builder.Append("</MetaRawDataVault>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadRawLinkSatelliteList(MetaRawDataVaultModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawLinkSatelliteList");
                return;
            }

            reader.ReadStartElement("RawLinkSatelliteList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "RawLinkSatellite", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'RawLinkSatelliteList'.");
                }
                var row = ReadRawLinkSatellite(reader, relationshipBuffers);
                loadState.AddRawLinkSatelliteId(row.Id);
                model.RawLinkSatelliteList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static RawLinkSatellite ReadRawLinkSatellite(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new RawLinkSatellite();
            var relationships = new RawLinkSatelliteRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "RawLinkId":
                            relationships.RawLinkId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'RawLinkSatellite'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawLinkSatellite");
                (relationshipBuffers.RawLinkSatelliteRelationships ??= new List<RawLinkSatelliteRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("RawLinkSatellite");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    case "SatelliteKind":
                        row.SatelliteKind = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'RawLinkSatellite'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.RawLinkSatelliteRelationships ??= new List<RawLinkSatelliteRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeRawLinkSatelliteShard(MetaRawDataVaultModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaRawDataVault>\n");
            builder.Append("  <RawLinkSatelliteList>\n");
            foreach (var row in model.RawLinkSatelliteList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'RawLinkSatellite' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'RawLinkSatellite' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <RawLinkSatellite Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var rawLinkId = RequireIdentity(row.RawLink?.Id, $"Relationship 'RawLinkSatellite.RawLinkId' on row 'RawLinkSatellite:{row.Id}' is empty.");
                if (!saveIndexes.RawLinkListById.TryGetValue(rawLinkId, out var rawLinkCanonical) || !ReferenceEquals(rawLinkCanonical, row.RawLink))
                {
                    throw new InvalidOperationException($"Relationship 'RawLinkSatellite.RawLinkId' on row 'RawLinkSatellite:{row.Id}' references an object that is not the canonical row for Id '{rawLinkId}'.");
                }
                builder.Append(' ');
                builder.Append("RawLinkId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, rawLinkId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'RawLinkSatellite' row '{row.Id}' is missing required property 'Name'."), "      ");
                AppendElement(builder, "SatelliteKind", RequireText(row.SatelliteKind, $"Entity 'RawLinkSatellite' row '{row.Id}' is missing required property 'SatelliteKind'."), "      ");
                builder.Append("    </RawLinkSatellite>\n");
            }
            builder.Append("  </RawLinkSatelliteList>\n");
            builder.Append("</MetaRawDataVault>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private static void LoadRawLinkSatelliteAttributeList(MetaRawDataVaultModel model, XmlReader reader, LoadState loadState, RelationshipBuffers relationshipBuffers)
        {
            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawLinkSatelliteAttributeList");
                return;
            }

            reader.ReadStartElement("RawLinkSatelliteAttributeList");
            while (reader.NodeType == XmlNodeType.Element)
            {
                if (!string.Equals(reader.LocalName, "RawLinkSatelliteAttribute", StringComparison.Ordinal))
                {
                    throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' in 'RawLinkSatelliteAttributeList'.");
                }
                var row = ReadRawLinkSatelliteAttribute(reader, relationshipBuffers);
                loadState.AddRawLinkSatelliteAttributeId(row.Id);
                model.RawLinkSatelliteAttributeList.Add(row);
                reader.MoveToContent();
            }
            reader.ReadEndElement();
        }

        private static RawLinkSatelliteAttribute ReadRawLinkSatelliteAttribute(XmlReader reader, RelationshipBuffers relationshipBuffers)
        {
            var row = new RawLinkSatelliteAttribute();
            var relationships = new RawLinkSatelliteAttributeRelationships { Row = row };
            if (reader.HasAttributes)
            {
                while (reader.MoveToNextAttribute())
                {
                    if (IsNamespaceDeclaration(reader))
                    {
                        continue;
                    }

                    switch (reader.LocalName)
                    {
                        case "Id":
                            row.Id = reader.Value;
                            break;
                        case "FieldId":
                            relationships.FieldId = reader.Value;
                            break;
                        case "RawLinkSatelliteId":
                            relationships.RawLinkSatelliteId = reader.Value;
                            break;
                        default:
                            throw new InvalidDataException($"Unknown XML attribute '{reader.LocalName}' on 'RawLinkSatelliteAttribute'.");
                    }
                }

                reader.MoveToElement();
            }

            if (reader.IsEmptyElement)
            {
                reader.ReadStartElement("RawLinkSatelliteAttribute");
                (relationshipBuffers.RawLinkSatelliteAttributeRelationships ??= new List<RawLinkSatelliteAttributeRelationships>()).Add(relationships);
                return row;
            }

            reader.ReadStartElement("RawLinkSatelliteAttribute");
            while (reader.NodeType == XmlNodeType.Element)
            {
                switch (reader.LocalName)
                {
                    case "Name":
                        row.Name = reader.ReadElementContentAsString();
                        break;
                    case "Ordinal":
                        row.Ordinal = reader.ReadElementContentAsString();
                        break;
                    default:
                        throw new InvalidDataException($"Unknown XML element '{reader.LocalName}' on 'RawLinkSatelliteAttribute'.");
                }
            }
            reader.ReadEndElement();
            (relationshipBuffers.RawLinkSatelliteAttributeRelationships ??= new List<RawLinkSatelliteAttributeRelationships>()).Add(relationships);
            return row;
        }

        private static byte[] SerializeRawLinkSatelliteAttributeShard(MetaRawDataVaultModel model, SaveIndexes saveIndexes)
        {
            var builder = new StringBuilder();
            var rowIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            builder.Append("<MetaRawDataVault>\n");
            builder.Append("  <RawLinkSatelliteAttributeList>\n");
            foreach (var row in model.RawLinkSatelliteAttributeList.OrderBy(row => row.Id, StringComparer.OrdinalIgnoreCase))
            {
                ArgumentNullException.ThrowIfNull(row);
                var rowId = RequireIdentity(row.Id, "Entity 'RawLinkSatelliteAttribute' contains a row with empty Id.");
                if (!rowIds.Add(rowId))
                {
                    throw new InvalidOperationException($"Entity 'RawLinkSatelliteAttribute' contains duplicate Id '{rowId}'.");
                }
                builder.Append("    <RawLinkSatelliteAttribute Id=\"");
                AppendXmlAttribute(builder, rowId);
                builder.Append('"');
                var fieldId = RequireIdentity(row.Field?.Id, $"Relationship 'RawLinkSatelliteAttribute.FieldId' on row 'RawLinkSatelliteAttribute:{row.Id}' is empty.");
                if (!saveIndexes.FieldListById.TryGetValue(fieldId, out var fieldCanonical) || !ReferenceEquals(fieldCanonical, row.Field))
                {
                    throw new InvalidOperationException($"Relationship 'RawLinkSatelliteAttribute.FieldId' on row 'RawLinkSatelliteAttribute:{row.Id}' references an object that is not the canonical row for Id '{fieldId}'.");
                }
                builder.Append(' ');
                builder.Append("FieldId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, fieldId);
                builder.Append('"');
                var rawLinkSatelliteId = RequireIdentity(row.RawLinkSatellite?.Id, $"Relationship 'RawLinkSatelliteAttribute.RawLinkSatelliteId' on row 'RawLinkSatelliteAttribute:{row.Id}' is empty.");
                if (!saveIndexes.RawLinkSatelliteListById.TryGetValue(rawLinkSatelliteId, out var rawLinkSatelliteCanonical) || !ReferenceEquals(rawLinkSatelliteCanonical, row.RawLinkSatellite))
                {
                    throw new InvalidOperationException($"Relationship 'RawLinkSatelliteAttribute.RawLinkSatelliteId' on row 'RawLinkSatelliteAttribute:{row.Id}' references an object that is not the canonical row for Id '{rawLinkSatelliteId}'.");
                }
                builder.Append(' ');
                builder.Append("RawLinkSatelliteId");
                builder.Append("=\"");
                AppendXmlAttribute(builder, rawLinkSatelliteId);
                builder.Append('"');
                builder.Append(">\n");
                AppendElement(builder, "Name", RequireText(row.Name, $"Entity 'RawLinkSatelliteAttribute' row '{row.Id}' is missing required property 'Name'."), "      ");
                AppendElement(builder, "Ordinal", RequireText(row.Ordinal, $"Entity 'RawLinkSatelliteAttribute' row '{row.Id}' is missing required property 'Ordinal'."), "      ");
                builder.Append("    </RawLinkSatelliteAttribute>\n");
            }
            builder.Append("  </RawLinkSatelliteAttributeList>\n");
            builder.Append("</MetaRawDataVault>\n");
            return Utf8NoBom.GetBytes(builder.ToString());
        }

        private sealed class FieldDataTypeDetailRelationships
        {
            public FieldDataTypeDetail Row { get; set; } = null!;
            public string FieldId { get; set; } = string.Empty;
        }

        private sealed class RawHubKeyPartRelationships
        {
            public RawHubKeyPart Row { get; set; } = null!;
            public string FieldId { get; set; } = string.Empty;
            public string RawHubId { get; set; } = string.Empty;
        }

        private sealed class RawHubSatelliteRelationships
        {
            public RawHubSatellite Row { get; set; } = null!;
            public string RawHubId { get; set; } = string.Empty;
        }

        private sealed class RawHubSatelliteAttributeRelationships
        {
            public RawHubSatelliteAttribute Row { get; set; } = null!;
            public string FieldId { get; set; } = string.Empty;
            public string RawHubSatelliteId { get; set; } = string.Empty;
        }

        private sealed class RawLinkHubRelationships
        {
            public RawLinkHub Row { get; set; } = null!;
            public string RawHubId { get; set; } = string.Empty;
            public string RawLinkId { get; set; } = string.Empty;
        }

        private sealed class RawLinkSatelliteRelationships
        {
            public RawLinkSatellite Row { get; set; } = null!;
            public string RawLinkId { get; set; } = string.Empty;
        }

        private sealed class RawLinkSatelliteAttributeRelationships
        {
            public RawLinkSatelliteAttribute Row { get; set; } = null!;
            public string FieldId { get; set; } = string.Empty;
            public string RawLinkSatelliteId { get; set; } = string.Empty;
        }

        private sealed class RelationshipBuffers
        {
            public List<FieldDataTypeDetailRelationships>? FieldDataTypeDetailRelationships { get; set; }
            public List<RawHubKeyPartRelationships>? RawHubKeyPartRelationships { get; set; }
            public List<RawHubSatelliteRelationships>? RawHubSatelliteRelationships { get; set; }
            public List<RawHubSatelliteAttributeRelationships>? RawHubSatelliteAttributeRelationships { get; set; }
            public List<RawLinkHubRelationships>? RawLinkHubRelationships { get; set; }
            public List<RawLinkSatelliteRelationships>? RawLinkSatelliteRelationships { get; set; }
            public List<RawLinkSatelliteAttributeRelationships>? RawLinkSatelliteAttributeRelationships { get; set; }
        }

        private static void ResolveRelationshipGroup1(LoadIndexes loadIndexes, RelationshipBuffers relationshipBuffers)
        {
            foreach (var relationship in relationshipBuffers.FieldDataTypeDetailRelationships ?? Enumerable.Empty<FieldDataTypeDetailRelationships>())
            {
                relationship.Row.Field = RequireTarget(
                    loadIndexes.FieldListById,
                    relationship.FieldId,
                    "FieldDataTypeDetail",
                    relationship.Row.Id,
                    "FieldId");
            }

            foreach (var relationship in relationshipBuffers.RawHubKeyPartRelationships ?? Enumerable.Empty<RawHubKeyPartRelationships>())
            {
                relationship.Row.Field = RequireTarget(
                    loadIndexes.FieldListById,
                    relationship.FieldId,
                    "RawHubKeyPart",
                    relationship.Row.Id,
                    "FieldId");
            }

            foreach (var relationship in relationshipBuffers.RawHubKeyPartRelationships ?? Enumerable.Empty<RawHubKeyPartRelationships>())
            {
                relationship.Row.RawHub = RequireTarget(
                    loadIndexes.RawHubListById,
                    relationship.RawHubId,
                    "RawHubKeyPart",
                    relationship.Row.Id,
                    "RawHubId");
            }

            foreach (var relationship in relationshipBuffers.RawHubSatelliteRelationships ?? Enumerable.Empty<RawHubSatelliteRelationships>())
            {
                relationship.Row.RawHub = RequireTarget(
                    loadIndexes.RawHubListById,
                    relationship.RawHubId,
                    "RawHubSatellite",
                    relationship.Row.Id,
                    "RawHubId");
            }

            foreach (var relationship in relationshipBuffers.RawHubSatelliteAttributeRelationships ?? Enumerable.Empty<RawHubSatelliteAttributeRelationships>())
            {
                relationship.Row.Field = RequireTarget(
                    loadIndexes.FieldListById,
                    relationship.FieldId,
                    "RawHubSatelliteAttribute",
                    relationship.Row.Id,
                    "FieldId");
            }

            foreach (var relationship in relationshipBuffers.RawHubSatelliteAttributeRelationships ?? Enumerable.Empty<RawHubSatelliteAttributeRelationships>())
            {
                relationship.Row.RawHubSatellite = RequireTarget(
                    loadIndexes.RawHubSatelliteListById,
                    relationship.RawHubSatelliteId,
                    "RawHubSatelliteAttribute",
                    relationship.Row.Id,
                    "RawHubSatelliteId");
            }

            foreach (var relationship in relationshipBuffers.RawLinkHubRelationships ?? Enumerable.Empty<RawLinkHubRelationships>())
            {
                relationship.Row.RawHub = RequireTarget(
                    loadIndexes.RawHubListById,
                    relationship.RawHubId,
                    "RawLinkHub",
                    relationship.Row.Id,
                    "RawHubId");
            }

            foreach (var relationship in relationshipBuffers.RawLinkHubRelationships ?? Enumerable.Empty<RawLinkHubRelationships>())
            {
                relationship.Row.RawLink = RequireTarget(
                    loadIndexes.RawLinkListById,
                    relationship.RawLinkId,
                    "RawLinkHub",
                    relationship.Row.Id,
                    "RawLinkId");
            }

            foreach (var relationship in relationshipBuffers.RawLinkSatelliteRelationships ?? Enumerable.Empty<RawLinkSatelliteRelationships>())
            {
                relationship.Row.RawLink = RequireTarget(
                    loadIndexes.RawLinkListById,
                    relationship.RawLinkId,
                    "RawLinkSatellite",
                    relationship.Row.Id,
                    "RawLinkId");
            }

            foreach (var relationship in relationshipBuffers.RawLinkSatelliteAttributeRelationships ?? Enumerable.Empty<RawLinkSatelliteAttributeRelationships>())
            {
                relationship.Row.Field = RequireTarget(
                    loadIndexes.FieldListById,
                    relationship.FieldId,
                    "RawLinkSatelliteAttribute",
                    relationship.Row.Id,
                    "FieldId");
            }

            foreach (var relationship in relationshipBuffers.RawLinkSatelliteAttributeRelationships ?? Enumerable.Empty<RawLinkSatelliteAttributeRelationships>())
            {
                relationship.Row.RawLinkSatellite = RequireTarget(
                    loadIndexes.RawLinkSatelliteListById,
                    relationship.RawLinkSatelliteId,
                    "RawLinkSatelliteAttribute",
                    relationship.Row.Id,
                    "RawLinkSatelliteId");
            }

        }

        private static readonly string[] ShardFileNames =
        {
            "Field.xml",
            "FieldDataTypeDetail.xml",
            "RawHub.xml",
            "RawHubKeyPart.xml",
            "RawHubSatellite.xml",
            "RawHubSatelliteAttribute.xml",
            "RawLink.xml",
            "RawLinkHub.xml",
            "RawLinkSatellite.xml",
            "RawLinkSatelliteAttribute.xml",
        };

        private static HashSet<string> BuildExpectedShardPaths(string instanceDirectoryPath)
        {
            var expectedShardPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var shardFileName in ShardFileNames)
            {
                expectedShardPaths.Add(Path.GetFullPath(Path.Combine(instanceDirectoryPath, shardFileName)));
            }

            return expectedShardPaths;
        }

        private sealed class LoadState
        {
            private HashSet<string>? fieldIds;

            public void AddFieldId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'Field' contains a row with empty Id.");
                fieldIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!fieldIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'Field' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? fieldDataTypeDetailIds;

            public void AddFieldDataTypeDetailId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'FieldDataTypeDetail' contains a row with empty Id.");
                fieldDataTypeDetailIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!fieldDataTypeDetailIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'FieldDataTypeDetail' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? rawHubIds;

            public void AddRawHubId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'RawHub' contains a row with empty Id.");
                rawHubIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!rawHubIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'RawHub' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? rawHubKeyPartIds;

            public void AddRawHubKeyPartId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'RawHubKeyPart' contains a row with empty Id.");
                rawHubKeyPartIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!rawHubKeyPartIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'RawHubKeyPart' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? rawHubSatelliteIds;

            public void AddRawHubSatelliteId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'RawHubSatellite' contains a row with empty Id.");
                rawHubSatelliteIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!rawHubSatelliteIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'RawHubSatellite' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? rawHubSatelliteAttributeIds;

            public void AddRawHubSatelliteAttributeId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'RawHubSatelliteAttribute' contains a row with empty Id.");
                rawHubSatelliteAttributeIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!rawHubSatelliteAttributeIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'RawHubSatelliteAttribute' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? rawLinkIds;

            public void AddRawLinkId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'RawLink' contains a row with empty Id.");
                rawLinkIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!rawLinkIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'RawLink' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? rawLinkHubIds;

            public void AddRawLinkHubId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'RawLinkHub' contains a row with empty Id.");
                rawLinkHubIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!rawLinkHubIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'RawLinkHub' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? rawLinkSatelliteIds;

            public void AddRawLinkSatelliteId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'RawLinkSatellite' contains a row with empty Id.");
                rawLinkSatelliteIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!rawLinkSatelliteIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'RawLinkSatellite' contains duplicate Id '{normalizedId}'.");
                }
            }

            private HashSet<string>? rawLinkSatelliteAttributeIds;

            public void AddRawLinkSatelliteAttributeId(string? id)
            {
                var normalizedId = RequireIdentity(id, "Entity 'RawLinkSatelliteAttribute' contains a row with empty Id.");
                rawLinkSatelliteAttributeIds ??= new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (!rawLinkSatelliteAttributeIds.Add(normalizedId))
                {
                    throw new InvalidDataException($"Entity 'RawLinkSatelliteAttribute' contains duplicate Id '{normalizedId}'.");
                }
            }

        }

        private sealed class LoadIndexes
        {
            private readonly MetaRawDataVaultModel model;

            public LoadIndexes(MetaRawDataVaultModel model)
            {
                this.model = model;
            }

            private Dictionary<string, Field>? fieldListById;

            public Dictionary<string, Field> FieldListById => fieldListById ??= BuildById(model.FieldList, row => row.Id, "Field");

            private Dictionary<string, FieldDataTypeDetail>? fieldDataTypeDetailListById;

            public Dictionary<string, FieldDataTypeDetail> FieldDataTypeDetailListById => fieldDataTypeDetailListById ??= BuildById(model.FieldDataTypeDetailList, row => row.Id, "FieldDataTypeDetail");

            private Dictionary<string, RawHub>? rawHubListById;

            public Dictionary<string, RawHub> RawHubListById => rawHubListById ??= BuildById(model.RawHubList, row => row.Id, "RawHub");

            private Dictionary<string, RawHubKeyPart>? rawHubKeyPartListById;

            public Dictionary<string, RawHubKeyPart> RawHubKeyPartListById => rawHubKeyPartListById ??= BuildById(model.RawHubKeyPartList, row => row.Id, "RawHubKeyPart");

            private Dictionary<string, RawHubSatellite>? rawHubSatelliteListById;

            public Dictionary<string, RawHubSatellite> RawHubSatelliteListById => rawHubSatelliteListById ??= BuildById(model.RawHubSatelliteList, row => row.Id, "RawHubSatellite");

            private Dictionary<string, RawHubSatelliteAttribute>? rawHubSatelliteAttributeListById;

            public Dictionary<string, RawHubSatelliteAttribute> RawHubSatelliteAttributeListById => rawHubSatelliteAttributeListById ??= BuildById(model.RawHubSatelliteAttributeList, row => row.Id, "RawHubSatelliteAttribute");

            private Dictionary<string, RawLink>? rawLinkListById;

            public Dictionary<string, RawLink> RawLinkListById => rawLinkListById ??= BuildById(model.RawLinkList, row => row.Id, "RawLink");

            private Dictionary<string, RawLinkHub>? rawLinkHubListById;

            public Dictionary<string, RawLinkHub> RawLinkHubListById => rawLinkHubListById ??= BuildById(model.RawLinkHubList, row => row.Id, "RawLinkHub");

            private Dictionary<string, RawLinkSatellite>? rawLinkSatelliteListById;

            public Dictionary<string, RawLinkSatellite> RawLinkSatelliteListById => rawLinkSatelliteListById ??= BuildById(model.RawLinkSatelliteList, row => row.Id, "RawLinkSatellite");

            private Dictionary<string, RawLinkSatelliteAttribute>? rawLinkSatelliteAttributeListById;

            public Dictionary<string, RawLinkSatelliteAttribute> RawLinkSatelliteAttributeListById => rawLinkSatelliteAttributeListById ??= BuildById(model.RawLinkSatelliteAttributeList, row => row.Id, "RawLinkSatelliteAttribute");

        }

        private sealed class SaveIndexes
        {
            private readonly MetaRawDataVaultModel model;

            public SaveIndexes(MetaRawDataVaultModel model)
            {
                this.model = model;
            }

            private Dictionary<string, Field>? fieldListById;

            public Dictionary<string, Field> FieldListById => fieldListById ??= BuildById(model.FieldList, row => row.Id, "Field");

            private Dictionary<string, FieldDataTypeDetail>? fieldDataTypeDetailListById;

            public Dictionary<string, FieldDataTypeDetail> FieldDataTypeDetailListById => fieldDataTypeDetailListById ??= BuildById(model.FieldDataTypeDetailList, row => row.Id, "FieldDataTypeDetail");

            private Dictionary<string, RawHub>? rawHubListById;

            public Dictionary<string, RawHub> RawHubListById => rawHubListById ??= BuildById(model.RawHubList, row => row.Id, "RawHub");

            private Dictionary<string, RawHubKeyPart>? rawHubKeyPartListById;

            public Dictionary<string, RawHubKeyPart> RawHubKeyPartListById => rawHubKeyPartListById ??= BuildById(model.RawHubKeyPartList, row => row.Id, "RawHubKeyPart");

            private Dictionary<string, RawHubSatellite>? rawHubSatelliteListById;

            public Dictionary<string, RawHubSatellite> RawHubSatelliteListById => rawHubSatelliteListById ??= BuildById(model.RawHubSatelliteList, row => row.Id, "RawHubSatellite");

            private Dictionary<string, RawHubSatelliteAttribute>? rawHubSatelliteAttributeListById;

            public Dictionary<string, RawHubSatelliteAttribute> RawHubSatelliteAttributeListById => rawHubSatelliteAttributeListById ??= BuildById(model.RawHubSatelliteAttributeList, row => row.Id, "RawHubSatelliteAttribute");

            private Dictionary<string, RawLink>? rawLinkListById;

            public Dictionary<string, RawLink> RawLinkListById => rawLinkListById ??= BuildById(model.RawLinkList, row => row.Id, "RawLink");

            private Dictionary<string, RawLinkHub>? rawLinkHubListById;

            public Dictionary<string, RawLinkHub> RawLinkHubListById => rawLinkHubListById ??= BuildById(model.RawLinkHubList, row => row.Id, "RawLinkHub");

            private Dictionary<string, RawLinkSatellite>? rawLinkSatelliteListById;

            public Dictionary<string, RawLinkSatellite> RawLinkSatelliteListById => rawLinkSatelliteListById ??= BuildById(model.RawLinkSatelliteList, row => row.Id, "RawLinkSatellite");

            private Dictionary<string, RawLinkSatelliteAttribute>? rawLinkSatelliteAttributeListById;

            public Dictionary<string, RawLinkSatelliteAttribute> RawLinkSatelliteAttributeListById => rawLinkSatelliteAttributeListById ??= BuildById(model.RawLinkSatelliteAttributeList, row => row.Id, "RawLinkSatelliteAttribute");

        }

        private static readonly Lazy<bool> RuntimeExtendedShape = new(DetectRuntimeExtendedShape);

        private static bool HasRuntimeExtendedShape()
        {
            return RuntimeExtendedShape.Value;
        }

        private static bool DetectRuntimeExtendedShape()
        {
            if (HasRuntimeExtendedEntityShapeGroup1())
            {
                return true;
            }

            return HasUnexpectedModelLists();
        }

        private static bool HasRuntimeExtendedEntityShapeGroup1()
        {
            if (HasUnexpectedProperties(typeof(Field),
                "Id",
                "DataTypeId",
                "Name"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(FieldDataTypeDetail),
                "Id",
                "Name",
                "Value",
                "Field"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(RawHub),
                "Id",
                "Name"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(RawHubKeyPart),
                "Id",
                "Name",
                "Ordinal",
                "Field",
                "RawHub"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(RawHubSatellite),
                "Id",
                "Name",
                "SatelliteKind",
                "RawHub"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(RawHubSatelliteAttribute),
                "Id",
                "Name",
                "Ordinal",
                "Field",
                "RawHubSatellite"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(RawLink),
                "Id",
                "LinkKind",
                "Name"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(RawLinkHub),
                "Id",
                "Ordinal",
                "RoleName",
                "RawHub",
                "RawLink"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(RawLinkSatellite),
                "Id",
                "Name",
                "SatelliteKind",
                "RawLink"))
            {
                return true;
            }

            if (HasUnexpectedProperties(typeof(RawLinkSatelliteAttribute),
                "Id",
                "Name",
                "Ordinal",
                "Field",
                "RawLinkSatellite"))
            {
                return true;
            }

            return false;
        }

        private static bool HasUnexpectedModelLists()
        {
            var knownLists = new HashSet<string>(StringComparer.Ordinal)
            {
                "FieldList",
                "FieldDataTypeDetailList",
                "RawHubList",
                "RawHubKeyPartList",
                "RawHubSatelliteList",
                "RawHubSatelliteAttributeList",
                "RawLinkList",
                "RawLinkHubList",
                "RawLinkSatelliteList",
                "RawLinkSatelliteAttributeList",
            };
            return typeof(MetaRawDataVaultModel).GetProperties(BindingFlags.Instance | BindingFlags.Public)
                .Any(property =>
                    property.PropertyType.IsGenericType &&
                    property.PropertyType.GetGenericTypeDefinition() == typeof(List<>) &&
                    !knownLists.Contains(property.Name));
        }

        private static bool HasUnexpectedProperties(Type type, params string[] knownProperties)
        {
            return type.GetProperties(BindingFlags.Instance | BindingFlags.Public)
                .Where(property => property.CanRead && property.CanWrite && property.GetIndexParameters().Length == 0)
                .Any(property => !knownProperties.Contains(property.Name, StringComparer.Ordinal));
        }

        private static Dictionary<string, T> BuildById<T>(IEnumerable<T> rows, Func<T, string> getId, string entityName)
            where T : class
        {
            var rowsById = new Dictionary<string, T>(StringComparer.OrdinalIgnoreCase);
            foreach (var row in rows)
            {
                ArgumentNullException.ThrowIfNull(row);
                var id = RequireIdentity(getId(row), $"Entity '{entityName}' contains a row with empty Id.");
                if (!rowsById.TryAdd(id, row))
                {
                    throw new InvalidOperationException($"Entity '{entityName}' contains duplicate Id '{id}'.");
                }
            }
            return rowsById;
        }

        private static T RequireTarget<T>(Dictionary<string, T> rowsById, string targetId, string sourceEntityName, string sourceId, string relationshipName)
            where T : class
        {
            var normalizedTargetId = RequireIdentity(targetId, $"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' is empty.");
            if (!rowsById.TryGetValue(normalizedTargetId, out var target))
            {
                throw new InvalidDataException($"Relationship '{sourceEntityName}.{relationshipName}' on row '{sourceEntityName}:{sourceId}' points to missing Id '{normalizedTargetId}'.");
            }
            return target;
        }

        private static string RequireIdentity(string? value, string errorMessage)
        {
            var normalizedValue = value?.Trim() ?? string.Empty;
            if (string.IsNullOrEmpty(normalizedValue))
            {
                throw new InvalidOperationException(errorMessage);
            }
            return normalizedValue;
        }

        private static string RequireText(string? value, string errorMessage)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new InvalidOperationException(errorMessage);
            }
            return value;
        }

        private static void AppendElement(StringBuilder builder, string name, string value, string indent)
        {
            builder.Append(indent);
            builder.Append('<');
            builder.Append(name);
            builder.Append('>');
            AppendXmlText(builder, value);
            builder.Append("</");
            builder.Append(name);
            builder.Append(">\n");
        }

        private static void AppendXmlAttribute(StringBuilder builder, string value)
        {
            foreach (var character in value)
            {
                switch (character)
                {
                    case '&': builder.Append("&amp;"); break;
                    case '<': builder.Append("&lt;"); break;
                    case '>': builder.Append("&gt;"); break;
                    case '"': builder.Append("&quot;"); break;
                    case '\'': builder.Append("&apos;"); break;
                    default: builder.Append(character); break;
                }
            }
        }

        private static void AppendXmlText(StringBuilder builder, string value)
        {
            foreach (var character in value)
            {
                switch (character)
                {
                    case '&': builder.Append("&amp;"); break;
                    case '<': builder.Append("&lt;"); break;
                    case '>': builder.Append("&gt;"); break;
                    default: builder.Append(character); break;
                }
            }
        }

        private static bool IsNamespaceDeclaration(XmlReader reader)
        {
            return string.Equals(reader.Prefix, "xmlns", StringComparison.Ordinal) ||
                   string.Equals(reader.LocalName, "xmlns", StringComparison.Ordinal);
        }

        private static void DeleteIfExists(string path)
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
        }

    }

}
