// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaRawDataVault
// Regenerate with:
//   meta generate csharp --workspace ".\MetaRawDataVault" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaRawDataVault
{
    public sealed class RawLinkHub
    {
        public string Id { get; set; } = string.Empty;

        public string Ordinal { get; set; } = string.Empty;

        public string? RoleName { get; set; }

        public RawHub RawHub { get; set; } = null!;

        public RawLink RawLink { get; set; } = null!;

    }
}
