// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaRawDataVault
// Regenerate with:
//   meta generate csharp --workspace ".\MetaRawDataVault" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaRawDataVault
{
    public sealed class SourceTableRelationshipField
    {
        public string Id { get; set; } = string.Empty;

        public string Ordinal { get; set; } = string.Empty;

        public SourceField SourceField { get; set; } = null!;

        public SourceTableRelationship SourceTableRelationship { get; set; } = null!;

        public SourceField TargetField { get; set; } = null!;

    }
}
