// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaDataWarehouseImplementation
// Regenerate with:
//   meta generate csharp --workspace ".\MetaDataWarehouseImplementation" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaDataWarehouseImplementation
{
    public sealed class BridgeTableImplementation
    {
        public string Id { get; set; } = string.Empty;

        public string ParticipantForeignKeyNamePattern { get; set; } = string.Empty;

        public string ParticipantKeyColumnPattern { get; set; } = string.Empty;

        public string PrimaryKeyNamePattern { get; set; } = string.Empty;

        public string SchemaName { get; set; } = string.Empty;

        public string TableNamePattern { get; set; } = string.Empty;

        public string? WeightColumnName { get; set; }

        public string? WeightDataTypeId { get; set; }

    }
}
