// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaDataWarehouseImplementation
// Regenerate with:
//   meta generate csharp --workspace ".\MetaDataWarehouseImplementation" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaDataWarehouseImplementation
{
    public sealed class DimensionTableImplementation
    {
        public string Id { get; set; } = string.Empty;

        public string AttributeColumnPattern { get; set; } = string.Empty;

        public string BusinessKeyColumnPattern { get; set; } = string.Empty;

        public string PrimaryKeyNamePattern { get; set; } = string.Empty;

        public string SchemaName { get; set; } = string.Empty;

        public string SurrogateKeyColumnName { get; set; } = string.Empty;

        public string SurrogateKeyDataTypeId { get; set; } = string.Empty;

        public string TableNamePattern { get; set; } = string.Empty;

    }
}
