// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaDataWarehouseImplementation
// Regenerate with:
//   meta generate csharp --workspace ".\MetaDataWarehouseImplementation" --out <dir> --tooling
// </auto-generated>

#nullable enable

using Meta.Core.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace MetaDataWarehouseImplementation
{
    public static class MetaDataWarehouseImplementationTooling
    {
        public static MetaDataWarehouseImplementationModel Load(
            string workspacePath,
            bool searchUpward = false)
        {
            return MetaDataWarehouseImplementationModel.LoadFromXmlWorkspace(workspacePath, searchUpward);
        }

        public static Task<MetaDataWarehouseImplementationModel> LoadAsync(
            string workspacePath,
            bool searchUpward = false,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return MetaDataWarehouseImplementationModel.LoadFromXmlWorkspaceAsync(workspacePath, searchUpward, cancellationToken);
        }

        public static string CreateWorkspace(string workspacePath)
        {
            return TypedWorkspaceXmlSerializer.CreateWorkspace<MetaDataWarehouseImplementationModel>(workspacePath);
        }

        public static bool IsWorkspace(string workspacePath)
        {
            return TypedWorkspaceXmlSerializer.IsWorkspace<MetaDataWarehouseImplementationModel>(workspacePath);
        }

        public static void Save(MetaDataWarehouseImplementationModel model, string workspacePath)
        {
            if (model == null)
            {
                throw new global::System.ArgumentNullException(nameof(model));
            }

            model.SaveToXmlWorkspace(workspacePath);
        }

        public static Task SaveAsync(MetaDataWarehouseImplementationModel model, string workspacePath,
            CancellationToken cancellationToken = default)
        {
            if (model == null)
            {
                throw new global::System.ArgumentNullException(nameof(model));
            }

            cancellationToken.ThrowIfCancellationRequested();
            model.SaveToXmlWorkspace(workspacePath);
            return Task.CompletedTask;
        }
    }
}
