// <auto-generated>
// This file was generated by Meta CLI.
// Do not edit this file by hand.
//
// Source workspace: .\MetaDataWarehouseImplementation
// Regenerate with:
//   meta generate csharp --workspace ".\MetaDataWarehouseImplementation" --out <dir> --tooling
// </auto-generated>

#nullable enable

namespace MetaDataWarehouseImplementation
{
    public sealed class PeriodicSnapshotFactTableImplementation
    {
        public string Id { get; set; } = string.Empty;

        public string PeriodDataTypeId { get; set; } = string.Empty;

        public string? PeriodEndColumnName { get; set; }

        public string PeriodStartColumnName { get; set; } = string.Empty;

    }
}
