USE [master];
GO

IF SUSER_ID(N'NT Service\MSOLAP$TABULAR') IS NULL
BEGIN
    CREATE LOGIN [NT Service\MSOLAP$TABULAR] FROM WINDOWS;
END;
GO

USE [AdventureWorksAnalytics];
GO

IF USER_ID(N'NT Service\MSOLAP$TABULAR') IS NULL
BEGIN
    CREATE USER [NT Service\MSOLAP$TABULAR]
        FOR LOGIN [NT Service\MSOLAP$TABULAR];
END;
GO

ALTER ROLE [db_datareader]
    ADD MEMBER [NT Service\MSOLAP$TABULAR];
GO
