<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tooling\MetaDataQuality.Tooling.csproj" />
    <ProjectReference Include="..\..\MetaTransform\Script\Tooling\MetaTransformScript.Tooling.csproj" />
    <ProjectReference Include="..\..\MetaTransform\Binding\Tooling\MetaTransformBinding.Tooling.csproj" />
  </ItemGroup>

</Project>
